from .cintillo_gui import Ui_CintilloV2
from .pantalla_de_login_gui import Ui_Login

from .pantalla_de_opciones_gui import Ui_PantallaDeOpciones

from .pantalla_admin_opciones_gui import Ui_PantallaDeOpcionesAdmin
from .pantalla_admin_crear_nuevo_usuario_gui import Ui_CrearNuevoUsuario
from .pantalla_admin_crear_respaldo_gui import Ui_PantallaCrearRespaldo

from .pantalla_de_vista_general_de_alumnos_gui import Ui_VistaGeneralDeAlumnos
from .pantalla_de_vista_general_del_personal_gui import Ui_VistaGeneralDelPersonal
from .pantalla_de_control_de_llegada_del_personal_gui import Ui_PantallaControlDeLlegada
from .pantalla_ver_perfil_completo_del_empleado_gui import Ui_PantallaInfoCompletaDelEmpleado
from .pantalla_ver_perfil_completo_del_alumno_gui import Ui_PantallaInfoCompletaDelAlumno
from .ventana_mostrar_diagnosticos_gui import Ui_VentanaMostrarDiagnosticoRegistrado
from .pantalla_control_de_reposo_del_personal_gui import Ui_PantallaControlReposoPersonal
from .ventana_añadir_reposos_empleado_gui import Ui_VentanaAnadirReposo


from .pantalla_formulario_registrar_nuevo_empleado_gui import Ui_PantallaFormularioEmpleado
from .pantalla_formulario_registrar_nuevo_alumno_gui import Ui_FormularioNuevoRegistroAlumnos
