# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1000, 611)
        Login.setMinimumSize(QtCore.QSize(1000, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.area_de_scroll = QtWidgets.QScrollArea(Login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_de_scroll.sizePolicy().hasHeightForWidth())
        self.area_de_scroll.setSizePolicy(sizePolicy)
        self.area_de_scroll.setStyleSheet("")
        self.area_de_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_de_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.area_de_scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.area_de_scroll.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.area_de_scroll.setWidgetResizable(True)
        self.area_de_scroll.setObjectName("area_de_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1000, 611))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_principal)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.espacio_a = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_a.sizePolicy().hasHeightForWidth())
        self.espacio_a.setSizePolicy(sizePolicy)
        self.espacio_a.setMinimumSize(QtCore.QSize(0, 0))
        self.espacio_a.setMaximumSize(QtCore.QSize(500, 16777215))
        self.espacio_a.setBaseSize(QtCore.QSize(0, 0))
        self.espacio_a.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 183, 72);\n"
"        \n"
"\n"
"\n"
"}")
        self.espacio_a.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_a.setFrameShadow(QtWidgets.QFrame.Plain)
        self.espacio_a.setObjectName("espacio_a")
        self.logo_del_tela = QtWidgets.QLabel(self.espacio_a)
        self.logo_del_tela.setGeometry(QtCore.QRect(110, 50, 261, 251))
        self.logo_del_tela.setText("")
        self.logo_del_tela.setPixmap(QtGui.QPixmap(".\\Elementos_graficos_ui\\../recursos_de_imagenes/Tela.png"))
        self.logo_del_tela.setScaledContents(True)
        self.logo_del_tela.setObjectName("logo_del_tela")
        self.mensaje_de_bienvenida = QtWidgets.QLabel(self.espacio_a)
        self.mensaje_de_bienvenida.setGeometry(QtCore.QRect(30, 310, 411, 81))
        self.mensaje_de_bienvenida.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    font: 87 18pt \"Arial\";\n"
"\n"
"}")
        self.mensaje_de_bienvenida.setAlignment(QtCore.Qt.AlignCenter)
        self.mensaje_de_bienvenida.setWordWrap(True)
        self.mensaje_de_bienvenida.setObjectName("mensaje_de_bienvenida")
        self.horizontalLayout.addWidget(self.espacio_a)
        self.espacio_b = QtWidgets.QFrame(self.espacio_principal)
        self.espacio_b.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255)\n"
"\n"
"\n"
"}")
        self.espacio_b.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_b.setFrameShadow(QtWidgets.QFrame.Plain)
        self.espacio_b.setObjectName("espacio_b")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.espacio_b)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.espacio_del_login = QtWidgets.QFrame(self.espacio_b)
        self.espacio_del_login.setMaximumSize(QtCore.QSize(350, 350))
        self.espacio_del_login.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 183, 72);\n"
"    border-radius: 30px;\n"
"        \n"
"\n"
"\n"
"}")
        self.espacio_del_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_del_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_del_login.setObjectName("espacio_del_login")
        self.titulo_login = QtWidgets.QLabel(self.espacio_del_login)
        self.titulo_login.setGeometry(QtCore.QRect(130, 20, 81, 41))
        self.titulo_login.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    font: 75 16pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_login.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_login.setObjectName("titulo_login")
        self.titulo_usuario = QtWidgets.QLabel(self.espacio_del_login)
        self.titulo_usuario.setGeometry(QtCore.QRect(30, 80, 91, 41))
        self.titulo_usuario.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_usuario.setObjectName("titulo_usuario")
        self.input_usuario = QtWidgets.QLineEdit(self.espacio_del_login)
        self.input_usuario.setGeometry(QtCore.QRect(30, 130, 291, 41))
        self.input_usuario.setStyleSheet("QLineEdit{\n"
"    \n"
"    font: 12pt \"Arial\";\n"
"    border-radius:20px;\n"
"    padding-left: 35px;\n"
"    padding-top:1px;\n"
"\n"
"\n"
"}")
        self.input_usuario.setObjectName("input_usuario")
        self.icono_usuario = QtWidgets.QLabel(self.espacio_del_login)
        self.icono_usuario.setGeometry(QtCore.QRect(40, 140, 21, 21))
        self.icono_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.icono_usuario.setText("")
        self.icono_usuario.setPixmap(QtGui.QPixmap(".\\Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/icono_de_usuario.png"))
        self.icono_usuario.setScaledContents(True)
        self.icono_usuario.setObjectName("icono_usuario")
        self.input_contrasena = QtWidgets.QLineEdit(self.espacio_del_login)
        self.input_contrasena.setGeometry(QtCore.QRect(30, 230, 291, 41))
        self.input_contrasena.setStyleSheet("QLineEdit{\n"
"    \n"
"    font: 12pt \"Arial\";\n"
"    border-radius:20px;\n"
"    padding-left: 35px;\n"
"    padding-top:1px;\n"
"\n"
"\n"
"}")
        self.input_contrasena.setText("")
        self.input_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_contrasena.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.input_contrasena.setObjectName("input_contrasena")
        self.titulo_usuario_2 = QtWidgets.QLabel(self.espacio_del_login)
        self.titulo_usuario_2.setGeometry(QtCore.QRect(30, 180, 121, 41))
        self.titulo_usuario_2.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_usuario_2.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_usuario_2.setObjectName("titulo_usuario_2")
        self.icono_contrasena = QtWidgets.QLabel(self.espacio_del_login)
        self.icono_contrasena.setGeometry(QtCore.QRect(40, 240, 21, 21))
        self.icono_contrasena.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.icono_contrasena.setText("")
        self.icono_contrasena.setPixmap(QtGui.QPixmap(".\\Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/icono_contraseña.png"))
        self.icono_contrasena.setScaledContents(True)
        self.icono_contrasena.setObjectName("icono_contrasena")
        self.boton_ingresar = QtWidgets.QPushButton(self.espacio_del_login)
        self.boton_ingresar.setGeometry(QtCore.QRect(130, 290, 91, 41))
        self.boton_ingresar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_ingresar.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_ingresar.setObjectName("boton_ingresar")
        self.boton_ver_contrasena = QtWidgets.QPushButton(self.espacio_del_login)
        self.boton_ver_contrasena.setGeometry(QtCore.QRect(280, 240, 31, 21))
        self.boton_ver_contrasena.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_ver_contrasena.setStyleSheet("QPushButton{\n"
"    border: 0px\n"
"\n"
"}")
        self.boton_ver_contrasena.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/ver_contraseña.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_ver_contrasena.setIcon(icon)
        self.boton_ver_contrasena.setIconSize(QtCore.QSize(25, 25))
        self.boton_ver_contrasena.setObjectName("boton_ver_contrasena")
        self.horizontalLayout_3.addWidget(self.espacio_del_login)
        self.horizontalLayout.addWidget(self.espacio_b)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.area_de_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.area_de_scroll)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Inicio de sesión"))
        self.mensaje_de_bienvenida.setText(_translate("Login", "Bienvenidos al nuevo Sistema de Información del T.E.L.A"))
        self.titulo_login.setText(_translate("Login", "Login"))
        self.titulo_usuario.setText(_translate("Login", "Usuario"))
        self.input_usuario.setPlaceholderText(_translate("Login", "Usuario"))
        self.input_contrasena.setPlaceholderText(_translate("Login", "Contraseña"))
        self.titulo_usuario_2.setText(_translate("Login", "Contraseña"))
        self.boton_ingresar.setText(_translate("Login", "Ingresar"))
