# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PantallaDeOpciones(object):
    def setupUi(self, PantallaDeOpeciones):
        PantallaDeOpeciones.setObjectName("PantallaDeOpeciones")
        PantallaDeOpeciones.resize(1027, 574)
        PantallaDeOpeciones.setStyleSheet("QWidget{\n"
"background-color: rgb(0, 183, 72);\n"
"    alternate-background-color: rgb(0, 183, 72);\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PantallaDeOpeciones)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.espacio_principal = QtWidgets.QFrame(PantallaDeOpeciones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_principal.sizePolicy().hasHeightForWidth())
        self.espacio_principal.setSizePolicy(sizePolicy)
        self.espacio_principal.setMinimumSize(QtCore.QSize(0, 0))
        self.espacio_principal.setStyleSheet("QFrame{\n"
"\n"
" background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e)\n"
"\n"
"}")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.espacio_para_titulo_y_boton = QtWidgets.QFrame(self.espacio_principal)
        self.espacio_para_titulo_y_boton.setMaximumSize(QtCore.QSize(16777215, 100))
        self.espacio_para_titulo_y_boton.setStyleSheet("background:transparent;")
        self.espacio_para_titulo_y_boton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_para_titulo_y_boton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_para_titulo_y_boton.setObjectName("espacio_para_titulo_y_boton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.espacio_para_titulo_y_boton)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.espacio_para_boton_de_regreso = QtWidgets.QFrame(self.espacio_para_titulo_y_boton)
        self.espacio_para_boton_de_regreso.setMaximumSize(QtCore.QSize(40, 16777215))
        self.espacio_para_boton_de_regreso.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_para_boton_de_regreso.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_para_boton_de_regreso.setObjectName("espacio_para_boton_de_regreso")
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_para_boton_de_regreso)
        self.boton_de_regreso.setGeometry(QtCore.QRect(0, 0, 40, 40))
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setMaximumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/flecha_izquierda_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_de_regreso.setIcon(icon)
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.horizontalLayout_2.addWidget(self.espacio_para_boton_de_regreso)
        self.titulo_de_las_opciones = QtWidgets.QLabel(self.espacio_para_titulo_y_boton)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_de_las_opciones.sizePolicy().hasHeightForWidth())
        self.titulo_de_las_opciones.setSizePolicy(sizePolicy)
        self.titulo_de_las_opciones.setMinimumSize(QtCore.QSize(400, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_de_las_opciones.setFont(font)
        self.titulo_de_las_opciones.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 138, 71);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.titulo_de_las_opciones.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_de_las_opciones.setObjectName("titulo_de_las_opciones")
        self.horizontalLayout_2.addWidget(self.titulo_de_las_opciones, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.espacio_para_titulo_y_boton)
        self.espacio_opciones = QtWidgets.QFrame(self.espacio_principal)
        self.espacio_opciones.setStyleSheet("background:transparent;")
        self.espacio_opciones.setObjectName("espacio_opciones")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_opciones)
        self.horizontalLayout.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.espacio_opcion_personal = QtWidgets.QFrame(self.espacio_opciones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_opcion_personal.sizePolicy().hasHeightForWidth())
        self.espacio_opcion_personal.setSizePolicy(sizePolicy)
        self.espacio_opcion_personal.setStyleSheet("background:transparent;")
        self.espacio_opcion_personal.setObjectName("espacio_opcion_personal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.espacio_opcion_personal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.boton_opcion_personal = QtWidgets.QPushButton(self.espacio_opcion_personal)
        self.boton_opcion_personal.setMinimumSize(QtCore.QSize(200, 50))
        self.boton_opcion_personal.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.boton_opcion_personal.setFont(font)
        self.boton_opcion_personal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_opcion_personal.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(0, 138, 71);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_opcion_personal.setObjectName("boton_opcion_personal")
        self.verticalLayout_3.addWidget(self.boton_opcion_personal, 0, QtCore.Qt.AlignHCenter)
        self.imagen_personal = QtWidgets.QLabel(self.espacio_opcion_personal)
        self.imagen_personal.setMinimumSize(QtCore.QSize(250, 250))
        self.imagen_personal.setMaximumSize(QtCore.QSize(200, 200))
        self.imagen_personal.setStyleSheet("QLabel{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid black;\n"
"    border-radius:60px;\n"
"\n"
"}")
        self.imagen_personal.setText("")
        self.imagen_personal.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/elementos_graficos_ui\\../recursos_de_imagenes/foto_personal.png"))
        self.imagen_personal.setScaledContents(True)
        self.imagen_personal.setObjectName("imagen_personal")
        self.verticalLayout_3.addWidget(self.imagen_personal, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.espacio_opcion_personal, 0, QtCore.Qt.AlignHCenter)
        self.espacio_opcion_alumnos = QtWidgets.QFrame(self.espacio_opciones)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_opcion_alumnos.sizePolicy().hasHeightForWidth())
        self.espacio_opcion_alumnos.setSizePolicy(sizePolicy)
        self.espacio_opcion_alumnos.setStyleSheet("background:transparent;")
        self.espacio_opcion_alumnos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_opcion_alumnos.setFrameShadow(QtWidgets.QFrame.Plain)
        self.espacio_opcion_alumnos.setObjectName("espacio_opcion_alumnos")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.espacio_opcion_alumnos)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.boton_opcion_alumno = QtWidgets.QPushButton(self.espacio_opcion_alumnos)
        self.boton_opcion_alumno.setMinimumSize(QtCore.QSize(200, 50))
        self.boton_opcion_alumno.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.boton_opcion_alumno.setFont(font)
        self.boton_opcion_alumno.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_opcion_alumno.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:rgb(0, 138, 71);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_opcion_alumno.setObjectName("boton_opcion_alumno")
        self.verticalLayout_2.addWidget(self.boton_opcion_alumno, 0, QtCore.Qt.AlignHCenter)
        self.imagen_alumno = QtWidgets.QLabel(self.espacio_opcion_alumnos)
        self.imagen_alumno.setMinimumSize(QtCore.QSize(250, 250))
        self.imagen_alumno.setMaximumSize(QtCore.QSize(200, 200))
        self.imagen_alumno.setStyleSheet("QLabel{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:2px solid black;\n"
"    border-radius:60px;\n"
"\n"
"}")
        self.imagen_alumno.setText("")
        self.imagen_alumno.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/elementos_graficos_ui\\../recursos_de_imagenes/foto_alumnos.png"))
        self.imagen_alumno.setScaledContents(True)
        self.imagen_alumno.setObjectName("imagen_alumno")
        self.verticalLayout_2.addWidget(self.imagen_alumno, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.espacio_opcion_alumnos, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.espacio_opciones)
        self.verticalLayout.addWidget(self.espacio_principal)

        self.retranslateUi(PantallaDeOpeciones)
        QtCore.QMetaObject.connectSlotsByName(PantallaDeOpeciones)

    def retranslateUi(self, PantallaDeOpeciones):
        _translate = QtCore.QCoreApplication.translate
        PantallaDeOpeciones.setWindowTitle(_translate("PantallaDeOpeciones", "Form"))
        self.titulo_de_las_opciones.setText(_translate("PantallaDeOpeciones", "Elige hacia dónde se va a dirigir"))
        self.boton_opcion_personal.setText(_translate("PantallaDeOpeciones", "Personal"))
        self.boton_opcion_alumno.setText(_translate("PantallaDeOpeciones", "Alumnos"))
