# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui/pantalla_admin_crear_nuevo_usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrearNuevoUsuario(object):
    def setupUi(self, CrearNuevoUsuario):
        CrearNuevoUsuario.setObjectName("CrearNuevoUsuario")
        CrearNuevoUsuario.resize(824, 640)
        CrearNuevoUsuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(CrearNuevoUsuario)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.area_de_scroll = QtWidgets.QScrollArea(CrearNuevoUsuario)
        self.area_de_scroll.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.area_de_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_de_scroll.setWidgetResizable(True)
        self.area_de_scroll.setObjectName("area_de_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 824, 640))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("background-color: rgb(0, 183, 72);")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.espacio_superior = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.espacio_superior.sizePolicy().hasHeightForWidth())
        self.espacio_superior.setSizePolicy(sizePolicy)
        self.espacio_superior.setMinimumSize(QtCore.QSize(0, 30))
        self.espacio_superior.setMaximumSize(QtCore.QSize(16777215, 70))
        self.espacio_superior.setObjectName("espacio_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.espacio_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_superior)
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(42, 42))
        self.boton_de_regreso.setMaximumSize(QtCore.QSize(42, 42))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/flecha_izquierda_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_de_regreso.setIcon(icon)
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.horizontalLayout_2.addWidget(self.boton_de_regreso, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label = QtWidgets.QLabel(self.espacio_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(320, 60))
        self.label.setMaximumSize(QtCore.QSize(320, 60))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    font: 75 18pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.espacio_superior, 0, QtCore.Qt.AlignTop)
        self.espacio_central = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.espacio_central.sizePolicy().hasHeightForWidth())
        self.espacio_central.setSizePolicy(sizePolicy)
        self.espacio_central.setMinimumSize(QtCore.QSize(700, 500))
        self.espacio_central.setMaximumSize(QtCore.QSize(16777215, 500))
        self.espacio_central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_central.setObjectName("espacio_central")
        self.input_nombre_real = QtWidgets.QLineEdit(self.espacio_central)
        self.input_nombre_real.setGeometry(QtCore.QRect(380, 100, 291, 41))
        self.input_nombre_real.setStyleSheet("QLineEdit{\n"
"    \n"
"    font: 12pt \"Arial\";\n"
"    border-radius:20px;\n"
"    padding-left: 35px;\n"
"    padding-top:1px;\n"
"    background:#ffffff;\n"
"\n"
"\n"
"}")
        self.input_nombre_real.setObjectName("input_nombre_real")
        self.input_contrasena = QtWidgets.QLineEdit(self.espacio_central)
        self.input_contrasena.setGeometry(QtCore.QRect(20, 200, 291, 41))
        self.input_contrasena.setStyleSheet("QLineEdit{\n"
"    \n"
"    font: 12pt \"Arial\";\n"
"    border-radius:20px;\n"
"    padding-left: 35px;\n"
"    padding-top:1px;\n"
"    background:#ffffff;\n"
"\n"
"\n"
"}")
        self.input_contrasena.setText("")
        self.input_contrasena.setEchoMode(QtWidgets.QLineEdit.Password)
        self.input_contrasena.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.input_contrasena.setObjectName("input_contrasena")
        self.icono_usuario = QtWidgets.QLabel(self.espacio_central)
        self.icono_usuario.setGeometry(QtCore.QRect(390, 110, 21, 21))
        self.icono_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.icono_usuario.setText("")
        self.icono_usuario.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/icono_de_usuario.png"))
        self.icono_usuario.setScaledContents(True)
        self.icono_usuario.setObjectName("icono_usuario")
        self.boton_roles = QtWidgets.QComboBox(self.espacio_central)
        self.boton_roles.setGeometry(QtCore.QRect(20, 300, 231, 41))
        self.boton_roles.setStyleSheet("QComboBox{\n"
"    background:#ffffff;\n"
"    font: 75 15pt \"Arial\";\n"
"    padding-left:15px;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #0078d7;   /* Borde azul cuando está en foco */\n"
"    background-color: #e0f7ff;   /* Fondo azul claro */\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #0078d7;   /* Borde azul cuando está en foco */\n"
"    background-color: #e0f7ff;   /* Fondo azul claro */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #ccc;\n"
"    background-color: white;\n"
"    color: #333;\n"
"    padding: 5px;  /* Margen interno de la lista */\n"
"    spacing: 10px; /* Espaciado entre los elementos (algunas versiones de Qt lo admiten) */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px; /* Espaciado interno de cada elemento */\n"
"    margin: 4px; /* Separación entre los elementos */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #c5c1c1;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.boton_roles.setFrame(False)
        self.boton_roles.setObjectName("boton_roles")
        self.boton_roles.addItem("")
        self.boton_roles.addItem("")
        self.boton_roles.addItem("")
        self.titulo_roles = QtWidgets.QLabel(self.espacio_central)
        self.titulo_roles.setGeometry(QtCore.QRect(20, 250, 71, 41))
        self.titulo_roles.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_roles.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_roles.setObjectName("titulo_roles")
        self.titulo_contrasena = QtWidgets.QLabel(self.espacio_central)
        self.titulo_contrasena.setGeometry(QtCore.QRect(20, 150, 121, 41))
        self.titulo_contrasena.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_contrasena.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_contrasena.setObjectName("titulo_contrasena")
        self.input_usuario = QtWidgets.QLineEdit(self.espacio_central)
        self.input_usuario.setGeometry(QtCore.QRect(20, 100, 291, 41))
        self.input_usuario.setStyleSheet("QLineEdit{\n"
"    \n"
"    font: 12pt \"Arial\";\n"
"    border-radius:20px;\n"
"    padding-left: 35px;\n"
"    padding-top:1px;\n"
"    background:#ffffff;\n"
"\n"
"\n"
"}")
        self.input_usuario.setObjectName("input_usuario")
        self.icono_contrasena = QtWidgets.QLabel(self.espacio_central)
        self.icono_contrasena.setGeometry(QtCore.QRect(30, 210, 21, 21))
        self.icono_contrasena.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.icono_contrasena.setText("")
        self.icono_contrasena.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/icono_contraseña.png"))
        self.icono_contrasena.setScaledContents(True)
        self.icono_contrasena.setObjectName("icono_contrasena")
        self.icono_usuario_2 = QtWidgets.QLabel(self.espacio_central)
        self.icono_usuario_2.setGeometry(QtCore.QRect(30, 110, 21, 21))
        self.icono_usuario_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;")
        self.icono_usuario_2.setText("")
        self.icono_usuario_2.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/icono_de_usuario.png"))
        self.icono_usuario_2.setScaledContents(True)
        self.icono_usuario_2.setObjectName("icono_usuario_2")
        self.titulo_usuario = QtWidgets.QLabel(self.espacio_central)
        self.titulo_usuario.setGeometry(QtCore.QRect(20, 50, 91, 41))
        self.titulo_usuario.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_usuario.setObjectName("titulo_usuario")
        self.titulo_nombre_real = QtWidgets.QLabel(self.espacio_central)
        self.titulo_nombre_real.setGeometry(QtCore.QRect(380, 50, 141, 41))
        self.titulo_nombre_real.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    \n"
"    \n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.titulo_nombre_real.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo_nombre_real.setObjectName("titulo_nombre_real")
        self.boton_crear_usuario = QtWidgets.QPushButton(self.espacio_central)
        self.boton_crear_usuario.setGeometry(QtCore.QRect(290, 370, 91, 41))
        self.boton_crear_usuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_crear_usuario.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"    font: 75 14pt \"Arial\";\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_crear_usuario.setObjectName("boton_crear_usuario")
        self.logo_tela = QtWidgets.QLabel(self.espacio_central)
        self.logo_tela.setGeometry(QtCore.QRect(400, 160, 211, 191))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_tela.sizePolicy().hasHeightForWidth())
        self.logo_tela.setSizePolicy(sizePolicy)
        self.logo_tela.setText("")
        self.logo_tela.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/Elementos_graficos_ui\\../recursos_de_imagenes/Tela.png"))
        self.logo_tela.setScaledContents(True)
        self.logo_tela.setObjectName("logo_tela")
        self.input_nombre_real.raise_()
        self.input_contrasena.raise_()
        self.input_usuario.raise_()
        self.icono_usuario.raise_()
        self.boton_roles.raise_()
        self.titulo_roles.raise_()
        self.titulo_contrasena.raise_()
        self.icono_contrasena.raise_()
        self.icono_usuario_2.raise_()
        self.titulo_usuario.raise_()
        self.titulo_nombre_real.raise_()
        self.boton_crear_usuario.raise_()
        self.logo_tela.raise_()
        self.verticalLayout.addWidget(self.espacio_central, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.area_de_scroll.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.area_de_scroll)

        self.retranslateUi(CrearNuevoUsuario)
        QtCore.QMetaObject.connectSlotsByName(CrearNuevoUsuario)

    def retranslateUi(self, CrearNuevoUsuario):
        _translate = QtCore.QCoreApplication.translate
        CrearNuevoUsuario.setWindowTitle(_translate("CrearNuevoUsuario", "Form"))
        self.label.setText(_translate("CrearNuevoUsuario", "Crear nuevo usuario"))
        self.input_nombre_real.setPlaceholderText(_translate("CrearNuevoUsuario", "Nombre real"))
        self.input_contrasena.setPlaceholderText(_translate("CrearNuevoUsuario", "Contraseña"))
        self.boton_roles.setItemText(0, _translate("CrearNuevoUsuario", "Rol 1"))
        self.boton_roles.setItemText(1, _translate("CrearNuevoUsuario", "Rol 2"))
        self.boton_roles.setItemText(2, _translate("CrearNuevoUsuario", "Rol 3"))
        self.titulo_roles.setText(_translate("CrearNuevoUsuario", "Roles"))
        self.titulo_contrasena.setText(_translate("CrearNuevoUsuario", "Contraseña"))
        self.input_usuario.setPlaceholderText(_translate("CrearNuevoUsuario", "Usuario"))
        self.titulo_usuario.setText(_translate("CrearNuevoUsuario", "Usuario"))
        self.titulo_nombre_real.setText(_translate("CrearNuevoUsuario", "Nombre real"))
        self.boton_crear_usuario.setText(_translate("CrearNuevoUsuario", "Crear"))
