from .alumnos.alumno_egresado import AlumnoEgresado
from .alumnos.alumno import Alumno
from .alumnos.asistencia_alumno import AsistenciaAlumno
from .empleados.asistencia_empleado import AsistenciaEmpleado
from .usuarios.auditoria import Auditoria
from .empleados.cargo_empleado import CargoEmpleado
from .empleados.detalle_cargo import DetalleCargo
from .diagnosticos.diagnostico import Diagnostico
from .empleados.empleado import Empleado
from .empleados.enfermedad_cronica import EnfermedadCronica
from .especialidades.especialidad import Especialidad
from .empleados.funcion_cargo import FuncionCargo
from .empleados.historial_enferm_cronicas import HistorialEnfermCronicas
from .alumnos.info_bancaria_alumno import InfoBancariaAlumno
from .alumnos.info_clinica_alumno import InfoClinicaAlumno
from .empleados.info_clinica_empleado import InfoClinicaEmpleado
from .empleados.info_laboral import InfoLaboral
from .alumnos.inscripcion import Inscripcion
from .alumnos.medidas_alumno import MedidasAlumno
from .usuarios.permiso_x_rol import PermisoXRol
from .usuarios.permiso import Permiso
from .empleados.reposo_empleado import ReposoEmpleado
from .alumnos.representante import Representante
from .usuarios.rol import Rol
from .empleados.tipo_cargo import TipoCargo
from .usuarios.usuario import Usuario