# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_CintilloV2(object):
    def setupUi(self, CintilloV2):
        CintilloV2.setObjectName("CintilloV2")
        CintilloV2.resize(762, 50)
        CintilloV2.setStyleSheet("border:1px solid black;")
        self.verticalLayout = QtWidgets.QVBoxLayout(CintilloV2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.espacio_princiapl = QtWidgets.QFrame(CintilloV2)
        self.espacio_princiapl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.espacio_princiapl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.espacio_princiapl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_princiapl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_princiapl.setObjectName("espacio_princiapl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_princiapl)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_zona_educativa = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_zona_educativa.sizePolicy().hasHeightForWidth())
        self.logo_zona_educativa.setSizePolicy(sizePolicy)
        self.logo_zona_educativa.setMaximumSize(QtCore.QSize(100, 40))
        self.logo_zona_educativa.setStyleSheet("border:none;")
        self.logo_zona_educativa.setText("")
        self.logo_zona_educativa.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/logo_zona_educativa.PNG")))
        self.logo_zona_educativa.setScaledContents(True)
        self.logo_zona_educativa.setObjectName("logo_zona_educativa")
        self.horizontalLayout.addWidget(self.logo_zona_educativa)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.membrete = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membrete.sizePolicy().hasHeightForWidth())
        self.membrete.setSizePolicy(sizePolicy)
        self.membrete.setMaximumSize(QtCore.QSize(230, 40))
        self.membrete.setStyleSheet("border:none;")
        self.membrete.setText("")
        self.membrete.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/membrete.PNG")))
        self.membrete.setScaledContents(True)
        self.membrete.setObjectName("membrete")
        self.horizontalLayout.addWidget(self.membrete)
        self.logo_tela = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_tela.sizePolicy().hasHeightForWidth())
        self.logo_tela.setSizePolicy(sizePolicy)
        self.logo_tela.setMinimumSize(QtCore.QSize(0, 0))
        self.logo_tela.setMaximumSize(QtCore.QSize(50, 40))
        self.logo_tela.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_tela.setBaseSize(QtCore.QSize(0, 0))
        self.logo_tela.setStyleSheet("border:none;")
        self.logo_tela.setText("")
        self.logo_tela.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/Tela.png")))
        self.logo_tela.setScaledContents(True)
        self.logo_tela.setObjectName("logo_tela")
        self.horizontalLayout.addWidget(self.logo_tela)
        spacerItem1 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.logo_juventud = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_juventud.sizePolicy().hasHeightForWidth())
        self.logo_juventud.setSizePolicy(sizePolicy)
        self.logo_juventud.setMaximumSize(QtCore.QSize(60, 40))
        self.logo_juventud.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_juventud.setStyleSheet("border:none;")
        self.logo_juventud.setText("")
        self.logo_juventud.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/logo_juventud.PNG")))
        self.logo_juventud.setScaledContents(True)
        self.logo_juventud.setObjectName("logo_juventud")
        self.horizontalLayout.addWidget(self.logo_juventud)
        self.verticalLayout.addWidget(self.espacio_princiapl)

        self.retranslateUi(CintilloV2)
        QtCore.QMetaObject.connectSlotsByName(CintilloV2)

    def retranslateUi(self, CintilloV2):
        _translate = QtCore.QCoreApplication.translate
        CintilloV2.setWindowTitle(_translate("CintilloV2", "Form"))