# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        VentanaPrincipal.setObjectName("VentanaPrincipal")
        VentanaPrincipal.resize(749, 583)
        self.centralwidget = QtWidgets.QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.espacio_princiapl = QtWidgets.QFrame(self.centralwidget)
        self.espacio_princiapl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.espacio_princiapl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.espacio_princiapl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_princiapl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_princiapl.setObjectName("espacio_princiapl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_princiapl)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_zona_educativa = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_zona_educativa.sizePolicy().hasHeightForWidth())
        self.logo_zona_educativa.setSizePolicy(sizePolicy)
        self.logo_zona_educativa.setMaximumSize(QtCore.QSize(100, 40))
        self.logo_zona_educativa.setStyleSheet("border:none;")
        self.logo_zona_educativa.setText("")
        self.logo_zona_educativa.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/logo_zona_educativa.PNG"))
        self.logo_zona_educativa.setScaledContents(True)
        self.logo_zona_educativa.setObjectName("logo_zona_educativa")
        self.horizontalLayout.addWidget(self.logo_zona_educativa)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.membrete = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membrete.sizePolicy().hasHeightForWidth())
        self.membrete.setSizePolicy(sizePolicy)
        self.membrete.setMaximumSize(QtCore.QSize(230, 40))
        self.membrete.setStyleSheet("border:none;")
        self.membrete.setText("")
        self.membrete.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/membrete.PNG"))
        self.membrete.setScaledContents(True)
        self.membrete.setObjectName("membrete")
        self.horizontalLayout.addWidget(self.membrete)
        self.logo_tela = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_tela.sizePolicy().hasHeightForWidth())
        self.logo_tela.setSizePolicy(sizePolicy)
        self.logo_tela.setMinimumSize(QtCore.QSize(0, 0))
        self.logo_tela.setMaximumSize(QtCore.QSize(50, 40))
        self.logo_tela.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_tela.setBaseSize(QtCore.QSize(0, 0))
        self.logo_tela.setStyleSheet("border:none;")
        self.logo_tela.setText("")
        self.logo_tela.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/Tela.png"))
        self.logo_tela.setScaledContents(True)
        self.logo_tela.setObjectName("logo_tela")
        self.horizontalLayout.addWidget(self.logo_tela)
        spacerItem1 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.logo_juventud = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_juventud.sizePolicy().hasHeightForWidth())
        self.logo_juventud.setSizePolicy(sizePolicy)
        self.logo_juventud.setMaximumSize(QtCore.QSize(60, 40))
        self.logo_juventud.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_juventud.setStyleSheet("border:none;")
        self.logo_juventud.setText("")
        self.logo_juventud.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/logo_juventud.PNG"))
        self.logo_juventud.setScaledContents(True)
        self.logo_juventud.setObjectName("logo_juventud")
        self.horizontalLayout.addWidget(self.logo_juventud)
        self.gridLayout.addWidget(self.espacio_princiapl, 0, 0, 1, 2)
        self.area_scroll_side_bar = QtWidgets.QScrollArea(self.centralwidget)
        self.area_scroll_side_bar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.area_scroll_side_bar.setStyleSheet("QScrollArea{\n"
"\n"
"    \n"
"    background-color: red;\n"
"}")
        self.area_scroll_side_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_scroll_side_bar.setWidgetResizable(True)
        self.area_scroll_side_bar.setObjectName("area_scroll_side_bar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 200, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.side_bar = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.side_bar.setMinimumSize(QtCore.QSize(181, 351))
        self.side_bar.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(0, 138, 71);\n"
"\n"
"\n"
"}")
        self.side_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout_2.setContentsMargins(5, 10, -1, -1)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.side_bar)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(40, 30))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/menu.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.pushButton_4 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/analisis_de_datos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setAutoRepeat(True)
        self.pushButton_4.setAutoExclusive(True)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/estudiantes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setCheckable(True)
        self.pushButton.setAutoRepeat(True)
        self.pushButton.setAutoExclusive(True)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_7 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/equipo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setAutoRepeat(True)
        self.pushButton_7.setAutoExclusive(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_2 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setAutoRepeat(True)
        self.pushButton_2.setAutoExclusive(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/base_de_datos_negra.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setAutoRepeat(True)
        self.pushButton_3.setAutoExclusive(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/folleto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_6.setCheckable(True)
        self.pushButton_6.setAutoRepeat(True)
        self.pushButton_6.setAutoExclusive(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        self.pushButton_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_5 = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    padding-left:10px;\n"
" \n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/recursos_graficos_y_logicos/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/cerrar_sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.side_bar)
        self.area_scroll_side_bar.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.area_scroll_side_bar, 1, 0, 1, 1)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stacked_widget, 1, 1, 1, 1)
        VentanaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipal)

    def retranslateUi(self, VentanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipal.setWindowTitle(_translate("VentanaPrincipal", "MainWindow"))
        self.label_3.setText(_translate("VentanaPrincipal", "MENU"))
        self.pushButton_4.setText(_translate("VentanaPrincipal", "DashBoard"))
        self.pushButton.setText(_translate("VentanaPrincipal", "Estudiantes"))
        self.pushButton_7.setText(_translate("VentanaPrincipal", "Personal"))
        self.pushButton_2.setText(_translate("VentanaPrincipal", "Personal"))
        self.pushButton_3.setText(_translate("VentanaPrincipal", "Respaldos"))
        self.pushButton_6.setText(_translate("VentanaPrincipal", "cargar catalogo"))
        self.pushButton_8.setText(_translate("VentanaPrincipal", "boton XD"))
        self.pushButton_5.setText(_translate("VentanaPrincipal", "salir"))