# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_PantallaGenerarInformesReportesAlumnos(object):
    def setupUi(self, PantallaGenerarInformesReportesAlumnos):
        PantallaGenerarInformesReportesAlumnos.setObjectName("PantallaGenerarInformesReportesAlumnos")
        PantallaGenerarInformesReportesAlumnos.resize(1345, 613)
        self.verticalLayout = QtWidgets.QVBoxLayout(PantallaGenerarInformesReportesAlumnos)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.area_de_scroll = QtWidgets.QScrollArea(PantallaGenerarInformesReportesAlumnos)
        self.area_de_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_de_scroll.setWidgetResizable(True)
        self.area_de_scroll.setObjectName("area_de_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1345, 613))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("QFrame{\n"
"\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e);\n"
"\n"
"}")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.gridLayout = QtWidgets.QGridLayout(self.espacio_principal)
        self.gridLayout.setObjectName("gridLayout")
        self.label_titulo_pantalla = QtWidgets.QLabel(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_pantalla.sizePolicy().hasHeightForWidth())
        self.label_titulo_pantalla.setSizePolicy(sizePolicy)
        self.label_titulo_pantalla.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_pantalla.setFont(font)
        self.label_titulo_pantalla.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"    padding:10px;\n"
"}")
        self.label_titulo_pantalla.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_pantalla.setWordWrap(True)
        self.label_titulo_pantalla.setObjectName("label_titulo_pantalla")
        self.gridLayout.addWidget(self.label_titulo_pantalla, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_principal)
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setMaximumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/flecha_izquierda_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_de_regreso.setIcon(icon)
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.gridLayout.addWidget(self.boton_de_regreso, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(241, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.espacio_principal)
        self.frame_4.setStyleSheet("QFrame{\n"
"\n"
"    background:none;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.espacio_para_las_opciones = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_para_las_opciones.sizePolicy().hasHeightForWidth())
        self.espacio_para_las_opciones.setSizePolicy(sizePolicy)
        self.espacio_para_las_opciones.setMinimumSize(QtCore.QSize(330, 90))
        self.espacio_para_las_opciones.setMaximumSize(QtCore.QSize(500, 16777215))
        self.espacio_para_las_opciones.setSizeIncrement(QtCore.QSize(0, 0))
        self.espacio_para_las_opciones.setStyleSheet("background:none;\n"
"border:none;")
        self.espacio_para_las_opciones.setFrameShadow(QtWidgets.QFrame.Plain)
        self.espacio_para_las_opciones.setObjectName("espacio_para_las_opciones")
        self.titulo_de_boton_de_opciones = QtWidgets.QLabel(self.espacio_para_las_opciones)
        self.titulo_de_boton_de_opciones.setGeometry(QtCore.QRect(33, 11, 305, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.titulo_de_boton_de_opciones.sizePolicy().hasHeightForWidth())
        self.titulo_de_boton_de_opciones.setSizePolicy(sizePolicy)
        self.titulo_de_boton_de_opciones.setMinimumSize(QtCore.QSize(0, 0))
        self.titulo_de_boton_de_opciones.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.titulo_de_boton_de_opciones.setFont(font)
        self.titulo_de_boton_de_opciones.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"}")
        self.titulo_de_boton_de_opciones.setObjectName("titulo_de_boton_de_opciones")
        self.boton_especialidades = QtWidgets.QComboBox(self.espacio_para_las_opciones)
        self.boton_especialidades.setGeometry(QtCore.QRect(34, 45, 305, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_especialidades.sizePolicy().hasHeightForWidth())
        self.boton_especialidades.setSizePolicy(sizePolicy)
        self.boton_especialidades.setMinimumSize(QtCore.QSize(305, 40))
        self.boton_especialidades.setStyleSheet("QComboBox{\n"
"\n"
"    font: 75 12pt \"Arial\";\n"
"    padding-left:15px;\n"
"    background:white;\n"
"    border:1px solid black;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #0078d7;   /* Borde azul cuando está en foco */\n"
"    background-color: #e0f7ff;   /* Fondo azul claro */\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid #0078d7;   /* Borde azul cuando está en foco */\n"
"    background-color: #e0f7ff;   /* Fondo azul claro */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid #ccc;\n"
"    background-color: white;\n"
"    color: #333;\n"
"    padding: 5px;  /* Margen interno de la lista */\n"
"    spacing: 10px; /* Espaciado entre los elementos (algunas versiones de Qt lo admiten) */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 8px; /* Espaciado interno de cada elemento */\n"
"    margin: 4px; /* Separación entre los elementos */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #c5c1c1;\n"
"    color: white;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.boton_especialidades.setEditable(False)
        self.boton_especialidades.setCurrentText("")
        self.boton_especialidades.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.boton_especialidades.setIconSize(QtCore.QSize(40, 40))
        self.boton_especialidades.setPlaceholderText("")
        self.boton_especialidades.setObjectName("boton_especialidades")
        self.verticalLayout_7.addWidget(self.espacio_para_las_opciones)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.espacio_informe_integral = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_informe_integral.sizePolicy().hasHeightForWidth())
        self.espacio_informe_integral.setSizePolicy(sizePolicy)
        self.espacio_informe_integral.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_informe_integral.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_informe_integral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_informe_integral.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_informe_integral.setObjectName("espacio_informe_integral")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.espacio_informe_integral)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_titulo_informe_educativo = QtWidgets.QLabel(self.espacio_informe_integral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo.setFont(font)
        self.label_titulo_informe_educativo.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(80, 80, 80);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo.setScaledContents(False)
        self.label_titulo_informe_educativo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo.setWordWrap(True)
        self.label_titulo_informe_educativo.setObjectName("label_titulo_informe_educativo")
        self.verticalLayout_4.addWidget(self.label_titulo_informe_educativo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_titulo_director_actual = QtWidgets.QLabel(self.espacio_informe_integral)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_director_actual.setFont(font)
        self.label_titulo_director_actual.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_titulo_director_actual.setObjectName("label_titulo_director_actual")
        self.horizontalLayout.addWidget(self.label_titulo_director_actual, 0, QtCore.Qt.AlignLeft)
        self.input_director_actual = QtWidgets.QLineEdit(self.espacio_informe_integral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_director_actual.sizePolicy().hasHeightForWidth())
        self.input_director_actual.setSizePolicy(sizePolicy)
        self.input_director_actual.setMinimumSize(QtCore.QSize(220, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_director_actual.setFont(font)
        self.input_director_actual.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_director_actual.setObjectName("input_director_actual")
        self.horizontalLayout.addWidget(self.input_director_actual)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.boton_generar_informe_integral = QtWidgets.QPushButton(self.espacio_informe_integral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_generar_informe_integral.sizePolicy().hasHeightForWidth())
        self.boton_generar_informe_integral.setSizePolicy(sizePolicy)
        self.boton_generar_informe_integral.setMinimumSize(QtCore.QSize(220, 40))
        self.boton_generar_informe_integral.setMaximumSize(QtCore.QSize(250, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_generar_informe_integral.setFont(font)
        self.boton_generar_informe_integral.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_generar_informe_integral.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/Enman/Documents/Enmanuel/trabajos uni Enmanuel/Proyecto Tela/Sistema_de_informacion_con_PyQt5/TELA-APP/elementos_graficos_ui\\../recursos_de_imagenes/iconos_de_interfaz/generar_informe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_generar_informe_integral.setIcon(icon1)
        self.boton_generar_informe_integral.setIconSize(QtCore.QSize(26, 26))
        self.boton_generar_informe_integral.setObjectName("boton_generar_informe_integral")
        self.verticalLayout_4.addWidget(self.boton_generar_informe_integral, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.espacio_informe_integral)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(388, 200))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_titulo_reporte_asistencia_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_reporte_asistencia_2.setFont(font)
        self.label_titulo_reporte_asistencia_2.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(80, 80, 80);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_reporte_asistencia_2.setScaledContents(False)
        self.label_titulo_reporte_asistencia_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_reporte_asistencia_2.setWordWrap(True)
        self.label_titulo_reporte_asistencia_2.setObjectName("label_titulo_reporte_asistencia_2")
        self.verticalLayout_5.addWidget(self.label_titulo_reporte_asistencia_2)
        self.boton_generar_informe_integral_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_generar_informe_integral_2.sizePolicy().hasHeightForWidth())
        self.boton_generar_informe_integral_2.setSizePolicy(sizePolicy)
        self.boton_generar_informe_integral_2.setMinimumSize(QtCore.QSize(220, 40))
        self.boton_generar_informe_integral_2.setMaximumSize(QtCore.QSize(250, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_generar_informe_integral_2.setFont(font)
        self.boton_generar_informe_integral_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_generar_informe_integral_2.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_generar_informe_integral_2.setIcon(icon1)
        self.boton_generar_informe_integral_2.setIconSize(QtCore.QSize(26, 26))
        self.boton_generar_informe_integral_2.setObjectName("boton_generar_informe_integral_2")
        self.verticalLayout_5.addWidget(self.boton_generar_informe_integral_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(388, 200))
        self.frame_3.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_titulo_reporte_asistencia = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_reporte_asistencia.setFont(font)
        self.label_titulo_reporte_asistencia.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(80, 80, 80);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_reporte_asistencia.setScaledContents(False)
        self.label_titulo_reporte_asistencia.setObjectName("label_titulo_reporte_asistencia")
        self.verticalLayout_3.addWidget(self.label_titulo_reporte_asistencia, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.boton_generar_informe_integral_3 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_generar_informe_integral_3.sizePolicy().hasHeightForWidth())
        self.boton_generar_informe_integral_3.setSizePolicy(sizePolicy)
        self.boton_generar_informe_integral_3.setMinimumSize(QtCore.QSize(300, 40))
        self.boton_generar_informe_integral_3.setMaximumSize(QtCore.QSize(250, 10))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_generar_informe_integral_3.setFont(font)
        self.boton_generar_informe_integral_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_generar_informe_integral_3.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_generar_informe_integral_3.setIcon(icon1)
        self.boton_generar_informe_integral_3.setIconSize(QtCore.QSize(26, 26))
        self.boton_generar_informe_integral_3.setObjectName("boton_generar_informe_integral_3")
        self.verticalLayout_3.addWidget(self.boton_generar_informe_integral_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem6)
        self.gridLayout.addWidget(self.frame_4, 1, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.area_de_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.area_de_scroll)

        self.retranslateUi(PantallaGenerarInformesReportesAlumnos)
        self.boton_especialidades.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(PantallaGenerarInformesReportesAlumnos)

    def retranslateUi(self, PantallaGenerarInformesReportesAlumnos):
        _translate = QtCore.QCoreApplication.translate
        PantallaGenerarInformesReportesAlumnos.setWindowTitle(_translate("PantallaGenerarInformesReportesAlumnos", "Form"))
        self.label_titulo_pantalla.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Generar informes o reportes de los alumnos"))
        self.titulo_de_boton_de_opciones.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Especialidad ocupacional"))
        self.label_titulo_informe_educativo.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Generar informe educativo integral"))
        self.label_titulo_director_actual.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Director/a actual:"))
        self.input_director_actual.setPlaceholderText(_translate("PantallaGenerarInformesReportesAlumnos", "....."))
        self.boton_generar_informe_integral.setText(_translate("PantallaGenerarInformesReportesAlumnos", "  Generar informe"))
        self.label_titulo_reporte_asistencia_2.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Generar reporte caracterización general"))
        self.boton_generar_informe_integral_2.setText(_translate("PantallaGenerarInformesReportesAlumnos", "  Generar reporte"))
        self.label_titulo_reporte_asistencia.setText(_translate("PantallaGenerarInformesReportesAlumnos", "Generar reporte de asistencia"))
        self.boton_generar_informe_integral_3.setText(_translate("PantallaGenerarInformesReportesAlumnos", "  Generar reporte de asistencia"))
