# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_PantallaControlReposoPersonal(object):
    def setupUi(self, PantallaControlReposoPersonal):
        PantallaControlReposoPersonal.setObjectName("PantallaControlReposoPersonal")
        PantallaControlReposoPersonal.resize(823, 501)
        self.verticalLayout = QtWidgets.QVBoxLayout(PantallaControlReposoPersonal)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(PantallaControlReposoPersonal)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -51, 822, 614))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("QFrame{\n"
"\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e)\n"
"   \n"
"\n"
"\n"
"}")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_principal)
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.horizontalLayout.addWidget(self.boton_de_regreso, 0, QtCore.Qt.AlignLeft)
        self.label_titulo_del_segemeto_opciones_admin = QtWidgets.QLabel(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_del_segemeto_opciones_admin.sizePolicy().hasHeightForWidth())
        self.label_titulo_del_segemeto_opciones_admin.setSizePolicy(sizePolicy)
        self.label_titulo_del_segemeto_opciones_admin.setMinimumSize(QtCore.QSize(300, 0))
        self.label_titulo_del_segemeto_opciones_admin.setMaximumSize(QtCore.QSize(700, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_del_segemeto_opciones_admin.setFont(font)
        self.label_titulo_del_segemeto_opciones_admin.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: #008a47;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.label_titulo_del_segemeto_opciones_admin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_del_segemeto_opciones_admin.setObjectName("label_titulo_del_segemeto_opciones_admin")
        self.horizontalLayout.addWidget(self.label_titulo_del_segemeto_opciones_admin, 0, QtCore.Qt.AlignLeft)
        self.espacio_para_barra_de_busqueda = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_para_barra_de_busqueda.sizePolicy().hasHeightForWidth())
        self.espacio_para_barra_de_busqueda.setSizePolicy(sizePolicy)
        self.espacio_para_barra_de_busqueda.setMinimumSize(QtCore.QSize(450, 90))
        self.espacio_para_barra_de_busqueda.setStyleSheet("background:transparent;")
        self.espacio_para_barra_de_busqueda.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_para_barra_de_busqueda.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_para_barra_de_busqueda.setObjectName("espacio_para_barra_de_busqueda")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.espacio_para_barra_de_busqueda)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.barra_de_busqueda = QtWidgets.QLineEdit(self.espacio_para_barra_de_busqueda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.barra_de_busqueda.sizePolicy().hasHeightForWidth())
        self.barra_de_busqueda.setSizePolicy(sizePolicy)
        self.barra_de_busqueda.setMinimumSize(QtCore.QSize(300, 40))
        self.barra_de_busqueda.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.barra_de_busqueda.setFont(font)
        self.barra_de_busqueda.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border:1px solid black  ;\n"
"    \n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.barra_de_busqueda.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_de_busqueda.setObjectName("barra_de_busqueda")
        self.horizontalLayout_3.addWidget(self.barra_de_busqueda)
        self.boton_buscar = QtWidgets.QPushButton(self.espacio_para_barra_de_busqueda)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.boton_buscar.sizePolicy().hasHeightForWidth())
        self.boton_buscar.setSizePolicy(sizePolicy)
        self.boton_buscar.setMinimumSize(QtCore.QSize(100, 40))
        self.boton_buscar.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_buscar.setFont(font)
        self.boton_buscar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_buscar.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_buscar.setIconSize(QtCore.QSize(25, 25))
        self.boton_buscar.setObjectName("boton_buscar")
        self.horizontalLayout_3.addWidget(self.boton_buscar)
        self.horizontalLayout.addWidget(self.espacio_para_barra_de_busqueda, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.setStretch(1, 10)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.espacio_tabla = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_tabla.sizePolicy().hasHeightForWidth())
        self.espacio_tabla.setSizePolicy(sizePolicy)
        self.espacio_tabla.setStyleSheet("QFrame{\n"
"\n"
"background:none;\n"
"\n"
"}")
        self.espacio_tabla.setObjectName("espacio_tabla")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.espacio_tabla)
        self.verticalLayout_3.setSpacing(30)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabla_personal_reposo = QtWidgets.QTableView(self.espacio_tabla)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabla_personal_reposo.sizePolicy().hasHeightForWidth())
        self.tabla_personal_reposo.setSizePolicy(sizePolicy)
        self.tabla_personal_reposo.setMinimumSize(QtCore.QSize(0, 400))
        self.tabla_personal_reposo.setStyleSheet("QTableView{\n"
"\n"
"background:none;\n"
"}")
        self.tabla_personal_reposo.setObjectName("tabla_personal_reposo")
        self.verticalLayout_3.addWidget(self.tabla_personal_reposo, 0, QtCore.Qt.AlignTop)
        self.boton_anadir_reposo = QtWidgets.QPushButton(self.espacio_tabla)
        self.boton_anadir_reposo.setMinimumSize(QtCore.QSize(190, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.boton_anadir_reposo.setFont(font)
        self.boton_anadir_reposo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_anadir_reposo.setStyleSheet("QPushButton{\n"
"\n"
"    \n"
"    background-color: rgb(64, 0, 255);\n"
"    color:#ffffff;\n"
"    border-radius:12px;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 19, 140);\n"
"    \n"
"    \n"
"\n"
"\n"
"}")
        self.boton_anadir_reposo.setIconSize(QtCore.QSize(30, 30))
        self.boton_anadir_reposo.setObjectName("boton_anadir_reposo")
        self.verticalLayout_3.addWidget(self.boton_anadir_reposo, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.espacio_tabla)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(PantallaControlReposoPersonal)
        QtCore.QMetaObject.connectSlotsByName(PantallaControlReposoPersonal)

    def retranslateUi(self, PantallaControlReposoPersonal):
        _translate = QtCore.QCoreApplication.translate
        PantallaControlReposoPersonal.setWindowTitle(_translate("PantallaControlReposoPersonal", "Form"))
        self.label_titulo_del_segemeto_opciones_admin.setText(_translate("PantallaControlReposoPersonal", "Control de reposos"))
        self.barra_de_busqueda.setPlaceholderText(_translate("PantallaControlReposoPersonal", "Buscar empleado por su cédula"))
        self.boton_buscar.setText(_translate("PantallaControlReposoPersonal", " Buscar"))
        self.boton_anadir_reposo.setText(_translate("PantallaControlReposoPersonal", "Añadir reposo"))