# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_PantallaInsertarCatalogoBD(object):
    def setupUi(self, PantallaInsertarCatalogoBD):
        PantallaInsertarCatalogoBD.setObjectName("PantallaInsertarCatalogoBD")
        PantallaInsertarCatalogoBD.resize(1247, 913)
        self.verticalLayout = QtWidgets.QVBoxLayout(PantallaInsertarCatalogoBD)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.area_de_scroll = QtWidgets.QScrollArea(PantallaInsertarCatalogoBD)
        self.area_de_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_de_scroll.setWidgetResizable(True)
        self.area_de_scroll.setObjectName("area_de_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -54, 1230, 967))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e)\n"
"   \n"
"")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_21.setContentsMargins(-1, 10, -1, -1)
        self.verticalLayout_21.setSpacing(20)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_principal)
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setMaximumSize(QtCore.QSize(40, 40))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/flecha_izquierda_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_de_regreso.setIcon(icon)
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.horizontalLayout.addWidget(self.boton_de_regreso, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_titulo_pantalla = QtWidgets.QLabel(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_pantalla.sizePolicy().hasHeightForWidth())
        self.label_titulo_pantalla.setSizePolicy(sizePolicy)
        self.label_titulo_pantalla.setMinimumSize(QtCore.QSize(500, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_pantalla.setFont(font)
        self.label_titulo_pantalla.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.label_titulo_pantalla.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_pantalla.setWordWrap(True)
        self.label_titulo_pantalla.setObjectName("label_titulo_pantalla")
        self.horizontalLayout.addWidget(self.label_titulo_pantalla)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_21.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.espacio_catalogo_especialidades = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_catalogo_especialidades.sizePolicy().hasHeightForWidth())
        self.espacio_catalogo_especialidades.setSizePolicy(sizePolicy)
        self.espacio_catalogo_especialidades.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_catalogo_especialidades.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_catalogo_especialidades.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_catalogo_especialidades.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_catalogo_especialidades.setObjectName("espacio_catalogo_especialidades")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.espacio_catalogo_especialidades)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_titulo_informe_educativo = QtWidgets.QLabel(self.espacio_catalogo_especialidades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo.setFont(font)
        self.label_titulo_informe_educativo.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo.setScaledContents(False)
        self.label_titulo_informe_educativo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo.setWordWrap(True)
        self.label_titulo_informe_educativo.setObjectName("label_titulo_informe_educativo")
        self.verticalLayout_5.addWidget(self.label_titulo_informe_educativo)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_especialidades = QtWidgets.QLabel(self.espacio_catalogo_especialidades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_especialidades.setFont(font)
        self.label_especialidades.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_especialidades.setObjectName("label_especialidades")
        self.verticalLayout_3.addWidget(self.label_especialidades, 0, QtCore.Qt.AlignLeft)
        self.input_especialidad = QtWidgets.QLineEdit(self.espacio_catalogo_especialidades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_especialidad.sizePolicy().hasHeightForWidth())
        self.input_especialidad.setSizePolicy(sizePolicy)
        self.input_especialidad.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_especialidad.setFont(font)
        self.input_especialidad.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_especialidad.setObjectName("input_especialidad")
        self.verticalLayout_3.addWidget(self.input_especialidad)
        self.boton_registrar_especialidad = QtWidgets.QPushButton(self.espacio_catalogo_especialidades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_registrar_especialidad.sizePolicy().hasHeightForWidth())
        self.boton_registrar_especialidad.setSizePolicy(sizePolicy)
        self.boton_registrar_especialidad.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_especialidad.setFont(font)
        self.boton_registrar_especialidad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_registrar_especialidad.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/mas_blanco.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_registrar_especialidad.setIcon(icon1)
        self.boton_registrar_especialidad.setIconSize(QtCore.QSize(26, 26))
        self.boton_registrar_especialidad.setObjectName("boton_registrar_especialidad")
        self.verticalLayout_3.addWidget(self.boton_registrar_especialidad, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.espacio_catalogo_especialidades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.vista_previa_especialidades = QtWidgets.QListWidget(self.espacio_catalogo_especialidades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.vista_previa_especialidades.setFont(font)
        self.vista_previa_especialidades.setToolTip("")
        self.vista_previa_especialidades.setStyleSheet("QListWidget{\n"
"\n"
"    border:1px solid black;\n"
"\n"
"\n"
"}")
        self.vista_previa_especialidades.setObjectName("vista_previa_especialidades")
        self.verticalLayout_4.addWidget(self.vista_previa_especialidades)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout.addWidget(self.espacio_catalogo_especialidades, 0, 0, 1, 1)
        self.espacio_catalogo_diagnostico = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_catalogo_diagnostico.sizePolicy().hasHeightForWidth())
        self.espacio_catalogo_diagnostico.setSizePolicy(sizePolicy)
        self.espacio_catalogo_diagnostico.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_catalogo_diagnostico.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_catalogo_diagnostico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_catalogo_diagnostico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_catalogo_diagnostico.setObjectName("espacio_catalogo_diagnostico")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.espacio_catalogo_diagnostico)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_titulo_informe_educativo_2 = QtWidgets.QLabel(self.espacio_catalogo_diagnostico)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo_2.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo_2.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo_2.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo_2.setFont(font)
        self.label_titulo_informe_educativo_2.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo_2.setScaledContents(False)
        self.label_titulo_informe_educativo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo_2.setWordWrap(True)
        self.label_titulo_informe_educativo_2.setObjectName("label_titulo_informe_educativo_2")
        self.verticalLayout_6.addWidget(self.label_titulo_informe_educativo_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_diagnostico = QtWidgets.QLabel(self.espacio_catalogo_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_diagnostico.setFont(font)
        self.label_diagnostico.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_diagnostico.setObjectName("label_diagnostico")
        self.verticalLayout_7.addWidget(self.label_diagnostico, 0, QtCore.Qt.AlignLeft)
        self.input_diagnostico = QtWidgets.QLineEdit(self.espacio_catalogo_diagnostico)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_diagnostico.sizePolicy().hasHeightForWidth())
        self.input_diagnostico.setSizePolicy(sizePolicy)
        self.input_diagnostico.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_diagnostico.setFont(font)
        self.input_diagnostico.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_diagnostico.setObjectName("input_diagnostico")
        self.verticalLayout_7.addWidget(self.input_diagnostico)
        self.boton_registrar_diagnostico = QtWidgets.QPushButton(self.espacio_catalogo_diagnostico)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_registrar_diagnostico.sizePolicy().hasHeightForWidth())
        self.boton_registrar_diagnostico.setSizePolicy(sizePolicy)
        self.boton_registrar_diagnostico.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_diagnostico.setFont(font)
        self.boton_registrar_diagnostico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_registrar_diagnostico.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_registrar_diagnostico.setIcon(icon1)
        self.boton_registrar_diagnostico.setIconSize(QtCore.QSize(26, 26))
        self.boton_registrar_diagnostico.setObjectName("boton_registrar_diagnostico")
        self.verticalLayout_7.addWidget(self.boton_registrar_diagnostico, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.espacio_catalogo_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.vista_previa_diagnosticos = QtWidgets.QListWidget(self.espacio_catalogo_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.vista_previa_diagnosticos.setFont(font)
        self.vista_previa_diagnosticos.setToolTip("")
        self.vista_previa_diagnosticos.setStyleSheet("QListWidget{\n"
"\n"
"    border:1px solid black;\n"
"\n"
"\n"
"}")
        self.vista_previa_diagnosticos.setObjectName("vista_previa_diagnosticos")
        self.verticalLayout_8.addWidget(self.vista_previa_diagnosticos)
        self.verticalLayout_6.addLayout(self.verticalLayout_8)
        self.gridLayout.addWidget(self.espacio_catalogo_diagnostico, 0, 1, 1, 1)
        self.espacio_catalogo_enfermedades = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_catalogo_enfermedades.sizePolicy().hasHeightForWidth())
        self.espacio_catalogo_enfermedades.setSizePolicy(sizePolicy)
        self.espacio_catalogo_enfermedades.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_catalogo_enfermedades.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_catalogo_enfermedades.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_catalogo_enfermedades.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_catalogo_enfermedades.setObjectName("espacio_catalogo_enfermedades")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.espacio_catalogo_enfermedades)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_titulo_informe_educativo_3 = QtWidgets.QLabel(self.espacio_catalogo_enfermedades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo_3.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo_3.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo_3.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo_3.setFont(font)
        self.label_titulo_informe_educativo_3.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo_3.setScaledContents(False)
        self.label_titulo_informe_educativo_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo_3.setWordWrap(True)
        self.label_titulo_informe_educativo_3.setObjectName("label_titulo_informe_educativo_3")
        self.verticalLayout_9.addWidget(self.label_titulo_informe_educativo_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_enfermedades = QtWidgets.QLabel(self.espacio_catalogo_enfermedades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_enfermedades.setFont(font)
        self.label_enfermedades.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_enfermedades.setObjectName("label_enfermedades")
        self.verticalLayout_10.addWidget(self.label_enfermedades, 0, QtCore.Qt.AlignLeft)
        self.input_enfermedad = QtWidgets.QLineEdit(self.espacio_catalogo_enfermedades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_enfermedad.sizePolicy().hasHeightForWidth())
        self.input_enfermedad.setSizePolicy(sizePolicy)
        self.input_enfermedad.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_enfermedad.setFont(font)
        self.input_enfermedad.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_enfermedad.setObjectName("input_enfermedad")
        self.verticalLayout_10.addWidget(self.input_enfermedad)
        self.boton_registrar_enfermedad = QtWidgets.QPushButton(self.espacio_catalogo_enfermedades)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_registrar_enfermedad.sizePolicy().hasHeightForWidth())
        self.boton_registrar_enfermedad.setSizePolicy(sizePolicy)
        self.boton_registrar_enfermedad.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_enfermedad.setFont(font)
        self.boton_registrar_enfermedad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_registrar_enfermedad.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_registrar_enfermedad.setIcon(icon1)
        self.boton_registrar_enfermedad.setIconSize(QtCore.QSize(26, 26))
        self.boton_registrar_enfermedad.setObjectName("boton_registrar_enfermedad")
        self.verticalLayout_10.addWidget(self.boton_registrar_enfermedad, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.espacio_catalogo_enfermedades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6, 0, QtCore.Qt.AlignLeft)
        self.vista_previa_enfermedades = QtWidgets.QListWidget(self.espacio_catalogo_enfermedades)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.vista_previa_enfermedades.setFont(font)
        self.vista_previa_enfermedades.setToolTip("")
        self.vista_previa_enfermedades.setStyleSheet("QListWidget{\n"
"\n"
"    border:1px solid black;\n"
"\n"
"\n"
"}")
        self.vista_previa_enfermedades.setObjectName("vista_previa_enfermedades")
        self.verticalLayout_11.addWidget(self.vista_previa_enfermedades)
        self.verticalLayout_9.addLayout(self.verticalLayout_11)
        self.gridLayout.addWidget(self.espacio_catalogo_enfermedades, 0, 2, 1, 1)
        self.espacio_catalogo_cargos_empleado = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_catalogo_cargos_empleado.sizePolicy().hasHeightForWidth())
        self.espacio_catalogo_cargos_empleado.setSizePolicy(sizePolicy)
        self.espacio_catalogo_cargos_empleado.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_catalogo_cargos_empleado.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_catalogo_cargos_empleado.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_catalogo_cargos_empleado.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_catalogo_cargos_empleado.setObjectName("espacio_catalogo_cargos_empleado")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.espacio_catalogo_cargos_empleado)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_titulo_informe_educativo_6 = QtWidgets.QLabel(self.espacio_catalogo_cargos_empleado)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo_6.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo_6.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo_6.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo_6.setFont(font)
        self.label_titulo_informe_educativo_6.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo_6.setScaledContents(False)
        self.label_titulo_informe_educativo_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo_6.setWordWrap(True)
        self.label_titulo_informe_educativo_6.setObjectName("label_titulo_informe_educativo_6")
        self.verticalLayout_18.addWidget(self.label_titulo_informe_educativo_6)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_cargo_empleado = QtWidgets.QLabel(self.espacio_catalogo_cargos_empleado)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cargo_empleado.setFont(font)
        self.label_cargo_empleado.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_cargo_empleado.setObjectName("label_cargo_empleado")
        self.verticalLayout_19.addWidget(self.label_cargo_empleado, 0, QtCore.Qt.AlignLeft)
        self.input_cargo_empleado = QtWidgets.QLineEdit(self.espacio_catalogo_cargos_empleado)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_cargo_empleado.sizePolicy().hasHeightForWidth())
        self.input_cargo_empleado.setSizePolicy(sizePolicy)
        self.input_cargo_empleado.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_cargo_empleado.setFont(font)
        self.input_cargo_empleado.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_cargo_empleado.setObjectName("input_cargo_empleado")
        self.verticalLayout_19.addWidget(self.input_cargo_empleado)
        self.boton_registrar_cargo_empleado = QtWidgets.QPushButton(self.espacio_catalogo_cargos_empleado)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_registrar_cargo_empleado.sizePolicy().hasHeightForWidth())
        self.boton_registrar_cargo_empleado.setSizePolicy(sizePolicy)
        self.boton_registrar_cargo_empleado.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_cargo_empleado.setFont(font)
        self.boton_registrar_cargo_empleado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_registrar_cargo_empleado.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_registrar_cargo_empleado.setIcon(icon1)
        self.boton_registrar_cargo_empleado.setIconSize(QtCore.QSize(26, 26))
        self.boton_registrar_cargo_empleado.setObjectName("boton_registrar_cargo_empleado")
        self.verticalLayout_19.addWidget(self.boton_registrar_cargo_empleado, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_12 = QtWidgets.QLabel(self.espacio_catalogo_cargos_empleado)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_20.addWidget(self.label_12, 0, QtCore.Qt.AlignLeft)
        self.vista_previa_cargos_empleados = QtWidgets.QListWidget(self.espacio_catalogo_cargos_empleado)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.vista_previa_cargos_empleados.setFont(font)
        self.vista_previa_cargos_empleados.setToolTip("")
        self.vista_previa_cargos_empleados.setStyleSheet("QListWidget{\n"
"\n"
"    border:1px solid black;\n"
"\n"
"\n"
"}")
        self.vista_previa_cargos_empleados.setObjectName("vista_previa_cargos_empleados")
        self.verticalLayout_20.addWidget(self.vista_previa_cargos_empleados)
        self.verticalLayout_18.addLayout(self.verticalLayout_20)
        self.gridLayout.addWidget(self.espacio_catalogo_cargos_empleado, 1, 0, 1, 1)
        self.espacio_catalogo_funciones_cargo = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.espacio_catalogo_funciones_cargo.sizePolicy().hasHeightForWidth())
        self.espacio_catalogo_funciones_cargo.setSizePolicy(sizePolicy)
        self.espacio_catalogo_funciones_cargo.setMinimumSize(QtCore.QSize(388, 200))
        self.espacio_catalogo_funciones_cargo.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:10px ridge rgb(122, 59, 33);\n"
"    padding:15px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.espacio_catalogo_funciones_cargo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_catalogo_funciones_cargo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_catalogo_funciones_cargo.setObjectName("espacio_catalogo_funciones_cargo")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.espacio_catalogo_funciones_cargo)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_titulo_informe_educativo_5 = QtWidgets.QLabel(self.espacio_catalogo_funciones_cargo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_titulo_informe_educativo_5.sizePolicy().hasHeightForWidth())
        self.label_titulo_informe_educativo_5.setSizePolicy(sizePolicy)
        self.label_titulo_informe_educativo_5.setMinimumSize(QtCore.QSize(320, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_informe_educativo_5.setFont(font)
        self.label_titulo_informe_educativo_5.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    border:none;\n"
"    border-color: #ffffff;\n"
"    padding:10px;\n"
"\n"
"\n"
"}\n"
"")
        self.label_titulo_informe_educativo_5.setScaledContents(False)
        self.label_titulo_informe_educativo_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_informe_educativo_5.setWordWrap(True)
        self.label_titulo_informe_educativo_5.setObjectName("label_titulo_informe_educativo_5")
        self.verticalLayout_15.addWidget(self.label_titulo_informe_educativo_5)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_funcion_cargo = QtWidgets.QLabel(self.espacio_catalogo_funciones_cargo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_funcion_cargo.setFont(font)
        self.label_funcion_cargo.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_funcion_cargo.setObjectName("label_funcion_cargo")
        self.verticalLayout_16.addWidget(self.label_funcion_cargo, 0, QtCore.Qt.AlignLeft)
        self.input_funcion_cargo = QtWidgets.QLineEdit(self.espacio_catalogo_funciones_cargo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input_funcion_cargo.sizePolicy().hasHeightForWidth())
        self.input_funcion_cargo.setSizePolicy(sizePolicy)
        self.input_funcion_cargo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_funcion_cargo.setFont(font)
        self.input_funcion_cargo.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_funcion_cargo.setObjectName("input_funcion_cargo")
        self.verticalLayout_16.addWidget(self.input_funcion_cargo)
        self.boton_registrar_funcion_cargo = QtWidgets.QPushButton(self.espacio_catalogo_funciones_cargo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_registrar_funcion_cargo.sizePolicy().hasHeightForWidth())
        self.boton_registrar_funcion_cargo.setSizePolicy(sizePolicy)
        self.boton_registrar_funcion_cargo.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_registrar_funcion_cargo.setFont(font)
        self.boton_registrar_funcion_cargo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_registrar_funcion_cargo.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: #008a47;\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_registrar_funcion_cargo.setIcon(icon1)
        self.boton_registrar_funcion_cargo.setIconSize(QtCore.QSize(26, 26))
        self.boton_registrar_funcion_cargo.setObjectName("boton_registrar_funcion_cargo")
        self.verticalLayout_16.addWidget(self.boton_registrar_funcion_cargo, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addLayout(self.verticalLayout_16)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_10 = QtWidgets.QLabel(self.espacio_catalogo_funciones_cargo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"\n"
"    border:none;\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_17.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.vista_previa_funciones_cargo = QtWidgets.QListWidget(self.espacio_catalogo_funciones_cargo)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.vista_previa_funciones_cargo.setFont(font)
        self.vista_previa_funciones_cargo.setToolTip("")
        self.vista_previa_funciones_cargo.setStyleSheet("QListWidget{\n"
"\n"
"    border:1px solid black;\n"
"\n"
"\n"
"}")
        self.vista_previa_funciones_cargo.setObjectName("vista_previa_funciones_cargo")
        self.verticalLayout_17.addWidget(self.vista_previa_funciones_cargo)
        self.verticalLayout_15.addLayout(self.verticalLayout_17)
        self.gridLayout.addWidget(self.espacio_catalogo_funciones_cargo, 1, 1, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.area_de_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.area_de_scroll)

        self.retranslateUi(PantallaInsertarCatalogoBD)
        QtCore.QMetaObject.connectSlotsByName(PantallaInsertarCatalogoBD)

    def retranslateUi(self, PantallaInsertarCatalogoBD):
        _translate = QtCore.QCoreApplication.translate
        PantallaInsertarCatalogoBD.setWindowTitle(_translate("PantallaInsertarCatalogoBD", "Form"))
        self.label_titulo_pantalla.setText(_translate("PantallaInsertarCatalogoBD", "Cargar catalogos del sistema de información"))
        self.label_titulo_informe_educativo.setText(_translate("PantallaInsertarCatalogoBD", "Catalogo de especialidades"))
        self.label_especialidades.setText(_translate("PantallaInsertarCatalogoBD", "Especialidad"))
        self.input_especialidad.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui va a escribir la especilidad nueva que falta"))
        self.input_especialidad.setPlaceholderText(_translate("PantallaInsertarCatalogoBD", "....."))
        self.boton_registrar_especialidad.setText(_translate("PantallaInsertarCatalogoBD", " Añadir"))
        self.label_2.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui estan todas las especialidades registradas"))
        self.label_2.setText(_translate("PantallaInsertarCatalogoBD", "Especialidad registradas"))
        self.label_titulo_informe_educativo_2.setText(_translate("PantallaInsertarCatalogoBD", "Catalogo de diagnostico"))
        self.label_diagnostico.setText(_translate("PantallaInsertarCatalogoBD", "Diagnostico"))
        self.input_diagnostico.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui va a escribir el diagnostico nuevo que falta"))
        self.input_diagnostico.setPlaceholderText(_translate("PantallaInsertarCatalogoBD", "....."))
        self.boton_registrar_diagnostico.setText(_translate("PantallaInsertarCatalogoBD", " Añadir"))
        self.label_4.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui estan todos los diagnosticos registrados"))
        self.label_4.setText(_translate("PantallaInsertarCatalogoBD", "Diagnosticos registrados"))
        self.label_titulo_informe_educativo_3.setText(_translate("PantallaInsertarCatalogoBD", "Catalogo de enfermedades"))
        self.label_enfermedades.setText(_translate("PantallaInsertarCatalogoBD", "Enfermedades"))
        self.input_enfermedad.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui va a escribir la enfermedad nueva que falta"))
        self.input_enfermedad.setPlaceholderText(_translate("PantallaInsertarCatalogoBD", "....."))
        self.boton_registrar_enfermedad.setText(_translate("PantallaInsertarCatalogoBD", " Añadir"))
        self.label_6.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui estan todas las enfermedades registradas"))
        self.label_6.setText(_translate("PantallaInsertarCatalogoBD", "Enfermedades registradas"))
        self.label_titulo_informe_educativo_6.setText(_translate("PantallaInsertarCatalogoBD", "Catalogo de cargos de empleados"))
        self.label_cargo_empleado.setText(_translate("PantallaInsertarCatalogoBD", "Cargo empleados"))
        self.input_cargo_empleado.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui va a escribir el cargo nuevo que falta"))
        self.input_cargo_empleado.setPlaceholderText(_translate("PantallaInsertarCatalogoBD", "....."))
        self.boton_registrar_cargo_empleado.setText(_translate("PantallaInsertarCatalogoBD", " Añadir"))
        self.label_12.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui estan todas las enfermedades registradas"))
        self.label_12.setText(_translate("PantallaInsertarCatalogoBD", "Cargos registrados"))
        self.label_titulo_informe_educativo_5.setText(_translate("PantallaInsertarCatalogoBD", "Catalogo de funciones de cargo"))
        self.label_funcion_cargo.setText(_translate("PantallaInsertarCatalogoBD", "Funcion de cargo"))
        self.input_funcion_cargo.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui va a escribir la funcion de cargo nueva que falta"))
        self.input_funcion_cargo.setPlaceholderText(_translate("PantallaInsertarCatalogoBD", "....."))
        self.boton_registrar_funcion_cargo.setText(_translate("PantallaInsertarCatalogoBD", " Añadir"))
        self.label_10.setToolTip(_translate("PantallaInsertarCatalogoBD", "Aqui estan todas las enfermedades registradas"))
        self.label_10.setText(_translate("PantallaInsertarCatalogoBD", "Funciones de cargo registrados"))