# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        VentanaPrincipal.setObjectName("VentanaPrincipal")
        VentanaPrincipal.resize(760, 583)
        VentanaPrincipal.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(VentanaPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, -1, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.espacio_princiapl = QtWidgets.QFrame(self.centralwidget)
        self.espacio_princiapl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.espacio_princiapl.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.espacio_princiapl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_princiapl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_princiapl.setObjectName("espacio_princiapl")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_princiapl)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo_zona_educativa = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_zona_educativa.sizePolicy().hasHeightForWidth())
        self.logo_zona_educativa.setSizePolicy(sizePolicy)
        self.logo_zona_educativa.setMaximumSize(QtCore.QSize(100, 40))
        self.logo_zona_educativa.setStyleSheet("border:none;")
        self.logo_zona_educativa.setText("")
        self.logo_zona_educativa.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/logo_zona_educativa.PNG")))
        self.logo_zona_educativa.setScaledContents(True)
        self.logo_zona_educativa.setObjectName("logo_zona_educativa")
        self.horizontalLayout.addWidget(self.logo_zona_educativa)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.membrete = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.membrete.sizePolicy().hasHeightForWidth())
        self.membrete.setSizePolicy(sizePolicy)
        self.membrete.setMaximumSize(QtCore.QSize(230, 40))
        self.membrete.setStyleSheet("border:none;")
        self.membrete.setText("")
        self.membrete.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/membrete.PNG")))
        self.membrete.setScaledContents(True)
        self.membrete.setObjectName("membrete")
        self.horizontalLayout.addWidget(self.membrete)
        self.logo_tela = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_tela.sizePolicy().hasHeightForWidth())
        self.logo_tela.setSizePolicy(sizePolicy)
        self.logo_tela.setMinimumSize(QtCore.QSize(0, 0))
        self.logo_tela.setMaximumSize(QtCore.QSize(50, 40))
        self.logo_tela.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_tela.setBaseSize(QtCore.QSize(0, 0))
        self.logo_tela.setStyleSheet("border:none;")
        self.logo_tela.setText("")
        self.logo_tela.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/Tela.png")))
        self.logo_tela.setScaledContents(True)
        self.logo_tela.setObjectName("logo_tela")
        self.horizontalLayout.addWidget(self.logo_tela)
        spacerItem1 = QtWidgets.QSpacerItem(133, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.logo_juventud = QtWidgets.QLabel(self.espacio_princiapl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo_juventud.sizePolicy().hasHeightForWidth())
        self.logo_juventud.setSizePolicy(sizePolicy)
        self.logo_juventud.setMaximumSize(QtCore.QSize(60, 40))
        self.logo_juventud.setSizeIncrement(QtCore.QSize(0, 0))
        self.logo_juventud.setStyleSheet("border:none;")
        self.logo_juventud.setText("")
        self.logo_juventud.setPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/logo_juventud.PNG")))
        self.logo_juventud.setScaledContents(True)
        self.logo_juventud.setObjectName("logo_juventud")
        self.horizontalLayout.addWidget(self.logo_juventud)
        self.gridLayout.addWidget(self.espacio_princiapl, 0, 0, 1, 2)
        self.area_scroll_side_bar = QtWidgets.QScrollArea(self.centralwidget)
        self.area_scroll_side_bar.setMaximumSize(QtCore.QSize(190, 16777215))
        self.area_scroll_side_bar.setStyleSheet("QScrollArea{\n"
"\n"
"    \n"
"    \n"
"    background-color: rgb(0, 138, 71);\n"
"    padding:0px 5px 0px 0px;\n"
"}")
        self.area_scroll_side_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_scroll_side_bar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.area_scroll_side_bar.setWidgetResizable(True)
        self.area_scroll_side_bar.setObjectName("area_scroll_side_bar")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 185, 524))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.side_bar = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.side_bar.setStyleSheet("QFrame{\n"
"\n"
"background-color: rgb(0, 138, 71);\n"
"}")
        self.side_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.side_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_bar.setObjectName("side_bar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_bar)
        self.verticalLayout_2.setContentsMargins(5, 10, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.side_bar)
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"    padding:0px 0px 0px 0px;\n"
"\n"
"}\n"
"")
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.boton_menu = QtWidgets.QPushButton(self.frame)
        self.boton_menu.setMaximumSize(QtCore.QSize(62, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_menu.setFont(font)
        self.boton_menu.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"\n"
"    padding:5px 0px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.boton_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/menu.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_menu.setIcon(icon)
        self.boton_menu.setIconSize(QtCore.QSize(30, 30))
        self.boton_menu.setCheckable(False)
        self.boton_menu.setAutoDefault(False)
        self.boton_menu.setDefault(False)
        self.boton_menu.setFlat(False)
        self.boton_menu.setObjectName("boton_menu")
        self.horizontalLayout_2.addWidget(self.boton_menu, 0, QtCore.Qt.AlignLeft)
        self.label_menu = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_menu.sizePolicy().hasHeightForWidth())
        self.label_menu.setSizePolicy(sizePolicy)
        self.label_menu.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_menu.setFont(font)
        self.label_menu.setStyleSheet("QLabel{\n"
"\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    padding:0px;\n"
"\n"
"}")
        self.label_menu.setObjectName("label_menu")
        self.horizontalLayout_2.addWidget(self.label_menu, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        self.line = QtWidgets.QFrame(self.side_bar)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.boton_principal = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_principal.setFont(font)
        self.boton_principal.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    padding:5px 0px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"    border-left:3px solid rgb(0, 183, 72);\n"
"    padding-left:4px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/hogar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_principal.setIcon(icon1)
        self.boton_principal.setIconSize(QtCore.QSize(30, 30))
        self.boton_principal.setCheckable(True)
        self.boton_principal.setAutoRepeat(True)
        self.boton_principal.setAutoExclusive(True)
        self.boton_principal.setObjectName("boton_principal")
        self.verticalLayout_2.addWidget(self.boton_principal)
        self.line_2 = QtWidgets.QFrame(self.side_bar)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.boton_estudiante = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_estudiante.setFont(font)
        self.boton_estudiante.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    padding:5px 0px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"    border-left:3px solid rgb(0, 183, 72);\n"
"    padding-left:4px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/estudiantes.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_estudiante.setIcon(icon2)
        self.boton_estudiante.setIconSize(QtCore.QSize(30, 30))
        self.boton_estudiante.setCheckable(True)
        self.boton_estudiante.setAutoRepeat(True)
        self.boton_estudiante.setAutoExclusive(True)
        self.boton_estudiante.setAutoDefault(False)
        self.boton_estudiante.setDefault(False)
        self.boton_estudiante.setFlat(False)
        self.boton_estudiante.setObjectName("boton_estudiante")
        self.verticalLayout_2.addWidget(self.boton_estudiante)
        self.line_3 = QtWidgets.QFrame(self.side_bar)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.boton_personal = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_personal.setFont(font)
        self.boton_personal.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    padding:5px 0px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"    border-left:3px solid rgb(0, 183, 72);\n"
"    padding-left:4px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/empleado.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_personal.setIcon(icon3)
        self.boton_personal.setIconSize(QtCore.QSize(30, 30))
        self.boton_personal.setCheckable(True)
        self.boton_personal.setAutoRepeat(True)
        self.boton_personal.setAutoExclusive(True)
        self.boton_personal.setObjectName("boton_personal")
        self.verticalLayout_2.addWidget(self.boton_personal)
        self.line_4 = QtWidgets.QFrame(self.side_bar)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.boton_respaldo = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_respaldo.setFont(font)
        self.boton_respaldo.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    padding:5px 0px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"    border-left:3px solid rgb(0, 183, 72);\n"
"    padding-left:4px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/respaldo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_respaldo.setIcon(icon4)
        self.boton_respaldo.setIconSize(QtCore.QSize(30, 30))
        self.boton_respaldo.setCheckable(True)
        self.boton_respaldo.setAutoRepeat(True)
        self.boton_respaldo.setAutoExclusive(True)
        self.boton_respaldo.setObjectName("boton_respaldo")
        self.verticalLayout_2.addWidget(self.boton_respaldo)
        self.line_6 = QtWidgets.QFrame(self.side_bar)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_2.addWidget(self.line_6)
        self.boton_cargar_catologo = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_cargar_catologo.setFont(font)
        self.boton_cargar_catologo.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    padding:5px 5px 5px 5px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"    border-left:3px solid rgb(0, 183, 72);\n"
"    padding-left:4px;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/catalogar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_cargar_catologo.setIcon(icon5)
        self.boton_cargar_catologo.setIconSize(QtCore.QSize(30, 30))
        self.boton_cargar_catologo.setCheckable(True)
        self.boton_cargar_catologo.setAutoRepeat(True)
        self.boton_cargar_catologo.setAutoExclusive(True)
        self.boton_cargar_catologo.setObjectName("boton_cargar_catologo")
        self.verticalLayout_2.addWidget(self.boton_cargar_catologo)
        self.line_7 = QtWidgets.QFrame(self.side_bar)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_2.addWidget(self.line_7)
        spacerItem2 = QtWidgets.QSpacerItem(20, 49, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.line_5 = QtWidgets.QFrame(self.side_bar)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.boton_salir = QtWidgets.QPushButton(self.side_bar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.boton_salir.setFont(font)
        self.boton_salir.setStyleSheet("QPushButton {\n"
"    /* Mantiene el icono a la izquierda y el texto más a la derecha */\n"
"    text-align: left;\n"
"    \n"
"\n"
"    background:transparent; \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"\n"
"    padding:5px 0px 5px 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"\n"
"\n"
"    \n"
"    background-color: rgb(0, 89, 45);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/cerrar_sesion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_salir.setIcon(icon6)
        self.boton_salir.setIconSize(QtCore.QSize(30, 30))
        self.boton_salir.setCheckable(False)
        self.boton_salir.setObjectName("boton_salir")
        self.verticalLayout_2.addWidget(self.boton_salir)
        self.line_8 = QtWidgets.QFrame(self.side_bar)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_2.addWidget(self.line_8)
        self.verticalLayout.addWidget(self.side_bar)
        self.area_scroll_side_bar.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.area_scroll_side_bar, 1, 0, 1, 1)
        self.stacked_widget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stacked_widget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stacked_widget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stacked_widget, 1, 1, 1, 1)
        VentanaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(VentanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipal)

    def retranslateUi(self, VentanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipal.setWindowTitle(_translate("VentanaPrincipal", "MainWindow"))
        self.label_menu.setText(_translate("VentanaPrincipal", "MENU"))
        self.boton_principal.setText(_translate("VentanaPrincipal", "  Principal"))
        self.boton_estudiante.setText(_translate("VentanaPrincipal", "  Estudiantes"))
        self.boton_personal.setText(_translate("VentanaPrincipal", "  Personal"))
        self.boton_respaldo.setText(_translate("VentanaPrincipal", "  Respaldos"))
        self.boton_cargar_catologo.setText(_translate("VentanaPrincipal", "  cargar catalogo"))
        self.boton_salir.setText(_translate("VentanaPrincipal", "salir"))