# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_PantallaCrearRespaldo(object):
    def setupUi(self, PantallaCrearRespaldo):
        PantallaCrearRespaldo.setObjectName("PantallaCrearRespaldo")
        PantallaCrearRespaldo.resize(1010, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(PantallaCrearRespaldo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.area_de_scroll = QtWidgets.QScrollArea(PantallaCrearRespaldo)
        self.area_de_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.area_de_scroll.setWidgetResizable(True)
        self.area_de_scroll.setObjectName("area_de_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1010, 640))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.espacio_principal = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.espacio_principal.setStyleSheet("\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e)\n"
"   \n"
"")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_4.setSpacing(40)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.espacio_superior = QtWidgets.QFrame(self.espacio_principal)
        self.espacio_superior.setMaximumSize(QtCore.QSize(16777215, 70))
        self.espacio_superior.setStyleSheet("background:transparent;")
        self.espacio_superior.setObjectName("espacio_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.espacio_superior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.boton_de_regreso = QtWidgets.QPushButton(self.espacio_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_de_regreso.sizePolicy().hasHeightForWidth())
        self.boton_de_regreso.setSizePolicy(sizePolicy)
        self.boton_de_regreso.setMinimumSize(QtCore.QSize(42, 42))
        self.boton_de_regreso.setMaximumSize(QtCore.QSize(42, 42))
        self.boton_de_regreso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_de_regreso.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 20px ;\n"
"    border:2px solid;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_de_regreso.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/flecha_izquierda_2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_de_regreso.setIcon(icon)
        self.boton_de_regreso.setIconSize(QtCore.QSize(30, 30))
        self.boton_de_regreso.setObjectName("boton_de_regreso")
        self.horizontalLayout.addWidget(self.boton_de_regreso, 0, QtCore.Qt.AlignLeft)
        self.label_crear_respaldo = QtWidgets.QLabel(self.espacio_superior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_crear_respaldo.sizePolicy().hasHeightForWidth())
        self.label_crear_respaldo.setSizePolicy(sizePolicy)
        self.label_crear_respaldo.setMinimumSize(QtCore.QSize(320, 60))
        self.label_crear_respaldo.setMaximumSize(QtCore.QSize(320, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_crear_respaldo.setFont(font)
        self.label_crear_respaldo.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.label_crear_respaldo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_crear_respaldo.setObjectName("label_crear_respaldo")
        self.horizontalLayout.addWidget(self.label_crear_respaldo, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_4.addWidget(self.espacio_superior)
        self.espacio_central = QtWidgets.QFrame(self.espacio_principal)
        self.espacio_central.setMinimumSize(QtCore.QSize(0, 0))
        self.espacio_central.setMaximumSize(QtCore.QSize(900, 16777215))
        self.espacio_central.setStyleSheet("background:transparent;")
        self.espacio_central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_central.setObjectName("espacio_central")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.espacio_central)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.espacio_requerimientos = QtWidgets.QFrame(self.espacio_central)
        self.espacio_requerimientos.setMinimumSize(QtCore.QSize(800, 220))
        self.espacio_requerimientos.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.espacio_requerimientos.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_requerimientos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_requerimientos.setObjectName("espacio_requerimientos")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.espacio_requerimientos)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.input_correo = QtWidgets.QLineEdit(self.espacio_requerimientos)
        self.input_correo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_correo.setFont(font)
        self.input_correo.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"\n"
"    border: 2px solid rgb(202, 202, 202);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_correo.setReadOnly(False)
        self.input_correo.setObjectName("input_correo")
        self.gridLayout.addWidget(self.input_correo, 1, 1, 1, 1)
        self.label_importar_datos = QtWidgets.QLineEdit(self.espacio_requerimientos)
        self.label_importar_datos.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_importar_datos.setFont(font)
        self.label_importar_datos.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"\n"
"    border: 2px solid rgb(202, 202, 202);\n"
"    \n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.label_importar_datos.setText("")
        self.label_importar_datos.setReadOnly(True)
        self.label_importar_datos.setObjectName("label_importar_datos")
        self.gridLayout.addWidget(self.label_importar_datos, 0, 1, 1, 1)
        self.label_titulo_importar = QtWidgets.QLabel(self.espacio_requerimientos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo_importar.setFont(font)
        self.label_titulo_importar.setStyleSheet("QLabel{\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_titulo_importar.setObjectName("label_titulo_importar")
        self.gridLayout.addWidget(self.label_titulo_importar, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_correo_asociado = QtWidgets.QLabel(self.espacio_requerimientos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_correo_asociado.setFont(font)
        self.label_correo_asociado.setStyleSheet("QLabel{\n"
"\n"
"        color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.label_correo_asociado.setObjectName("label_correo_asociado")
        self.gridLayout.addWidget(self.label_correo_asociado, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.boton_ruta_importar = QtWidgets.QPushButton(self.espacio_requerimientos)
        self.boton_ruta_importar.setMinimumSize(QtCore.QSize(70, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.boton_ruta_importar.setFont(font)
        self.boton_ruta_importar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_ruta_importar.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 183, 72);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        self.boton_ruta_importar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/base_de_datos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_ruta_importar.setIcon(icon1)
        self.boton_ruta_importar.setIconSize(QtCore.QSize(25, 25))
        self.boton_ruta_importar.setObjectName("boton_ruta_importar")
        self.gridLayout.addWidget(self.boton_ruta_importar, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.espacio_requerimientos, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.espacio_boton_opciones = QtWidgets.QFrame(self.espacio_central)
        self.espacio_boton_opciones.setStyleSheet("background:transparent;")
        self.espacio_boton_opciones.setObjectName("espacio_boton_opciones")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.espacio_boton_opciones)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(100)
        self.gridLayout_2.setVerticalSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.boton_exportar = QtWidgets.QPushButton(self.espacio_boton_opciones)
        self.boton_exportar.setMinimumSize(QtCore.QSize(347, 40))
        self.boton_exportar.setMaximumSize(QtCore.QSize(347, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_exportar.setFont(font)
        self.boton_exportar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_exportar.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"        color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/exportar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_exportar.setIcon(icon2)
        self.boton_exportar.setIconSize(QtCore.QSize(20, 20))
        self.boton_exportar.setObjectName("boton_exportar")
        self.gridLayout_2.addWidget(self.boton_exportar, 0, 0, 1, 1)
        self.boton_respaldo_correo = QtWidgets.QPushButton(self.espacio_boton_opciones)
        self.boton_respaldo_correo.setMinimumSize(QtCore.QSize(270, 40))
        self.boton_respaldo_correo.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_respaldo_correo.setFont(font)
        self.boton_respaldo_correo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_respaldo_correo.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"        color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/mail.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_respaldo_correo.setIcon(icon3)
        self.boton_respaldo_correo.setIconSize(QtCore.QSize(20, 20))
        self.boton_respaldo_correo.setObjectName("boton_respaldo_correo")
        self.gridLayout_2.addWidget(self.boton_respaldo_correo, 0, 1, 1, 1)
        self.boton_importar = QtWidgets.QPushButton(self.espacio_boton_opciones)
        self.boton_importar.setMinimumSize(QtCore.QSize(270, 40))
        self.boton_importar.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.boton_importar.setFont(font)
        self.boton_importar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_importar.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 112, 21);\n"
"        color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/importar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_importar.setIcon(icon4)
        self.boton_importar.setIconSize(QtCore.QSize(20, 20))
        self.boton_importar.setObjectName("boton_importar")
        self.gridLayout_2.addWidget(self.boton_importar, 1, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.espacio_boton_opciones, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_4.addWidget(self.espacio_central, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addWidget(self.espacio_principal)
        self.area_de_scroll.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.area_de_scroll)

        self.retranslateUi(PantallaCrearRespaldo)
        QtCore.QMetaObject.connectSlotsByName(PantallaCrearRespaldo)

    def retranslateUi(self, PantallaCrearRespaldo):
        _translate = QtCore.QCoreApplication.translate
        PantallaCrearRespaldo.setWindowTitle(_translate("PantallaCrearRespaldo", "Form"))
        self.label_crear_respaldo.setText(_translate("PantallaCrearRespaldo", "Importar/Exportar datos"))
        self.input_correo.setPlaceholderText(_translate("PantallaCrearRespaldo", "Aquí exportas los datos asociado un correo @gmail"))
        self.label_importar_datos.setPlaceholderText(_translate("PantallaCrearRespaldo", "Aquí se importan los datos nuevos"))
        self.label_titulo_importar.setText(_translate("PantallaCrearRespaldo", "Ruta del archivo .sql  para importar los datos:"))
        self.label_correo_asociado.setText(_translate("PantallaCrearRespaldo", "Correo asociado para exportar los datos:"))
        self.boton_exportar.setText(_translate("PantallaCrearRespaldo", " Exportar datos en la computadora "))
        self.boton_respaldo_correo.setText(_translate("PantallaCrearRespaldo", " Exportar datos al correo"))
        self.boton_importar.setText(_translate("PantallaCrearRespaldo", " Importar datos al sistema"))