# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_VentanaMostrarDiagnosticoRegistrado(object):
    def setupUi(self, VentanaMostrarDiagnosticoRegistrado):
        VentanaMostrarDiagnosticoRegistrado.setObjectName("VentanaMostrarDiagnosticoRegistrado")
        VentanaMostrarDiagnosticoRegistrado.setEnabled(True)
        VentanaMostrarDiagnosticoRegistrado.resize(607, 477)
        VentanaMostrarDiagnosticoRegistrado.setMinimumSize(QtCore.QSize(607, 477))
        VentanaMostrarDiagnosticoRegistrado.setMaximumSize(QtCore.QSize(607, 477))
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaMostrarDiagnosticoRegistrado)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.espacio_principal = QtWidgets.QFrame(VentanaMostrarDiagnosticoRegistrado)
        self.espacio_principal.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e)\n"
"   \n"
"}")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_8.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.titulo = QtWidgets.QLabel(self.espacio_principal)
        self.titulo.setMinimumSize(QtCore.QSize(230, 50))
        self.titulo.setMaximumSize(QtCore.QSize(230, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_8.addWidget(self.titulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.mostrar_diagnostico = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.mostrar_diagnostico.sizePolicy().hasHeightForWidth())
        self.mostrar_diagnostico.setSizePolicy(sizePolicy)
        self.mostrar_diagnostico.setMaximumSize(QtCore.QSize(500, 500))
        self.mostrar_diagnostico.setStyleSheet("QFrame{\n"
"\n"
"    background:#ffffff;\n"
"    border: 10px ridge rgb(122, 59, 33);\n"
"    \n"
"\n"
"\n"
"}")
        self.mostrar_diagnostico.setFrameShape(QtWidgets.QFrame.Box)
        self.mostrar_diagnostico.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mostrar_diagnostico.setObjectName("mostrar_diagnostico")
        self.formLayout = QtWidgets.QFormLayout(self.mostrar_diagnostico)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(20, 20, 20, 20)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_diagnostico = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_diagnostico.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_diagnostico.setFont(font)
        self.label_diagnostico.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_diagnostico.setScaledContents(True)
        self.label_diagnostico.setObjectName("label_diagnostico")
        self.verticalLayout_4.addWidget(self.label_diagnostico)
        self.label_mostrar_diagnostico = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_diagnostico.setMinimumSize(QtCore.QSize(437, 40))
        self.label_mostrar_diagnostico.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_diagnostico.setFont(font)
        self.label_mostrar_diagnostico.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_diagnostico.setText("")
        self.label_mostrar_diagnostico.setScaledContents(False)
        self.label_mostrar_diagnostico.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_diagnostico.setObjectName("label_mostrar_diagnostico")
        self.verticalLayout_4.addWidget(self.label_mostrar_diagnostico)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_fecha_diagnostico = QtWidgets.QLabel(self.mostrar_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_diagnostico.setFont(font)
        self.label_fecha_diagnostico.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_fecha_diagnostico.setScaledContents(True)
        self.label_fecha_diagnostico.setObjectName("label_fecha_diagnostico")
        self.verticalLayout_5.addWidget(self.label_fecha_diagnostico, 0, QtCore.Qt.AlignBottom)
        self.label_mostrar_fecha_diagnostico = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_fecha_diagnostico.setMinimumSize(QtCore.QSize(200, 40))
        self.label_mostrar_fecha_diagnostico.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_fecha_diagnostico.setFont(font)
        self.label_mostrar_fecha_diagnostico.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_fecha_diagnostico.setText("")
        self.label_mostrar_fecha_diagnostico.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_fecha_diagnostico.setObjectName("label_mostrar_fecha_diagnostico")
        self.verticalLayout_5.addWidget(self.label_mostrar_fecha_diagnostico)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_fecha_venc_certificado = QtWidgets.QLabel(self.mostrar_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fecha_venc_certificado.setFont(font)
        self.label_fecha_venc_certificado.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_fecha_venc_certificado.setScaledContents(True)
        self.label_fecha_venc_certificado.setWordWrap(True)
        self.label_fecha_venc_certificado.setObjectName("label_fecha_venc_certificado")
        self.verticalLayout_6.addWidget(self.label_fecha_venc_certificado)
        self.label_mostrar_fecha_venc_certificado = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_fecha_venc_certificado.setMinimumSize(QtCore.QSize(200, 40))
        self.label_mostrar_fecha_venc_certificado.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_fecha_venc_certificado.setFont(font)
        self.label_mostrar_fecha_venc_certificado.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_fecha_venc_certificado.setText("")
        self.label_mostrar_fecha_venc_certificado.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_fecha_venc_certificado.setObjectName("label_mostrar_fecha_venc_certificado")
        self.verticalLayout_6.addWidget(self.label_mostrar_fecha_venc_certificado)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_medico_tratante = QtWidgets.QLabel(self.mostrar_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_medico_tratante.setFont(font)
        self.label_medico_tratante.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_medico_tratante.setScaledContents(True)
        self.label_medico_tratante.setObjectName("label_medico_tratante")
        self.verticalLayout_7.addWidget(self.label_medico_tratante)
        self.label_mostrar_medico_tratante = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_medico_tratante.setMinimumSize(QtCore.QSize(200, 40))
        self.label_mostrar_medico_tratante.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_medico_tratante.setFont(font)
        self.label_mostrar_medico_tratante.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_medico_tratante.setText("")
        self.label_mostrar_medico_tratante.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_medico_tratante.setObjectName("label_mostrar_medico_tratante")
        self.verticalLayout_7.addWidget(self.label_mostrar_medico_tratante)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_certificado_discap = QtWidgets.QLabel(self.mostrar_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_certificado_discap.setFont(font)
        self.label_certificado_discap.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_certificado_discap.setScaledContents(True)
        self.label_certificado_discap.setObjectName("label_certificado_discap")
        self.verticalLayout_3.addWidget(self.label_certificado_discap)
        self.label_mostrar_certificado_discap = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_certificado_discap.setMinimumSize(QtCore.QSize(200, 40))
        self.label_mostrar_certificado_discap.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_certificado_discap.setFont(font)
        self.label_mostrar_certificado_discap.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_certificado_discap.setText("")
        self.label_mostrar_certificado_discap.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_certificado_discap.setObjectName("label_mostrar_certificado_discap")
        self.verticalLayout_3.addWidget(self.label_mostrar_certificado_discap)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_medicacion = QtWidgets.QLabel(self.mostrar_diagnostico)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_medicacion.setFont(font)
        self.label_medicacion.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_medicacion.setScaledContents(True)
        self.label_medicacion.setObjectName("label_medicacion")
        self.verticalLayout_2.addWidget(self.label_medicacion)
        self.label_mostrar_medicacion = QtWidgets.QLabel(self.mostrar_diagnostico)
        self.label_mostrar_medicacion.setMinimumSize(QtCore.QSize(200, 40))
        self.label_mostrar_medicacion.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_mostrar_medicacion.setFont(font)
        self.label_mostrar_medicacion.setStyleSheet("QLabel{\n"
"       background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"    }\n"
"    \n"
" ")
        self.label_mostrar_medicacion.setText("")
        self.label_mostrar_medicacion.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_mostrar_medicacion.setObjectName("label_mostrar_medicacion")
        self.verticalLayout_2.addWidget(self.label_mostrar_medicacion)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_2)
        self.verticalLayout_8.addWidget(self.mostrar_diagnostico, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.espacio_principal)

        self.retranslateUi(VentanaMostrarDiagnosticoRegistrado)
        QtCore.QMetaObject.connectSlotsByName(VentanaMostrarDiagnosticoRegistrado)

    def retranslateUi(self, VentanaMostrarDiagnosticoRegistrado):
        _translate = QtCore.QCoreApplication.translate
        VentanaMostrarDiagnosticoRegistrado.setWindowTitle(_translate("VentanaMostrarDiagnosticoRegistrado", "Form"))
        self.titulo.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Diagnóstico N° #"))
        self.label_diagnostico.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Diagnóstico"))
        self.label_fecha_diagnostico.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Fecha del diagnóstico"))
        self.label_fecha_venc_certificado.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Fecha de venc del certificado de discapacidad"))
        self.label_medico_tratante.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Medico Tratante"))
        self.label_certificado_discap.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Certificado de discapacidad"))
        self.label_medicacion.setText(_translate("VentanaMostrarDiagnosticoRegistrado", "Medicación"))