# -*- coding: utf-8 -*-

#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
BASE_DIR = os.path.dirname(__file__)


class Ui_VentanaAnadirReposo(object):
    def setupUi(self, VentanaAnadirReposo):
        VentanaAnadirReposo.setObjectName("VentanaAnadirReposo")
        VentanaAnadirReposo.resize(650, 500)
        VentanaAnadirReposo.setMaximumSize(QtCore.QSize(700, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaAnadirReposo)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.espacio_principal = QtWidgets.QFrame(VentanaAnadirReposo)
        self.espacio_principal.setStyleSheet("QFrame{\n"
"\n"
"    \n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #3fea87, stop:1 #00770e);\n"
"\n"
"}")
        self.espacio_principal.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.espacio_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.espacio_principal.setObjectName("espacio_principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.espacio_principal)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titulo = QtWidgets.QLabel(self.espacio_principal)
        self.titulo.setMinimumSize(QtCore.QSize(230, 50))
        self.titulo.setMaximumSize(QtCore.QSize(230, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(0, 112, 21);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"    border:none;\n"
"}")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.verticalLayout_4.addWidget(self.titulo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.ingresar_reposo = QtWidgets.QFrame(self.espacio_principal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.ingresar_reposo.sizePolicy().hasHeightForWidth())
        self.ingresar_reposo.setSizePolicy(sizePolicy)
        self.ingresar_reposo.setMinimumSize(QtCore.QSize(500, 370))
        self.ingresar_reposo.setMaximumSize(QtCore.QSize(500, 300))
        self.ingresar_reposo.setStyleSheet("QFrame{\n"
"\n"
"    background:#ffffff;\n"
"    border: 10px ridge rgb(122, 59, 33);\n"
"    \n"
"\n"
"\n"
"}")
        self.ingresar_reposo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ingresar_reposo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ingresar_reposo.setObjectName("ingresar_reposo")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ingresar_reposo)
        self.gridLayout_3.setContentsMargins(10, 20, 20, 20)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_cedula = QtWidgets.QLabel(self.ingresar_reposo)
        self.label_cedula.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cedula.setFont(font)
        self.label_cedula.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_cedula.setScaledContents(True)
        self.label_cedula.setObjectName("label_cedula")
        self.verticalLayout_2.addWidget(self.label_cedula)
        self.input_cedula = QtWidgets.QLineEdit(self.ingresar_reposo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.input_cedula.sizePolicy().hasHeightForWidth())
        self.input_cedula.setSizePolicy(sizePolicy)
        self.input_cedula.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_cedula.setFont(font)
        self.input_cedula.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_cedula.setObjectName("input_cedula")
        self.verticalLayout_2.addWidget(self.input_cedula)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_motivo_reposo = QtWidgets.QLabel(self.ingresar_reposo)
        self.label_motivo_reposo.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_motivo_reposo.setFont(font)
        self.label_motivo_reposo.setStyleSheet("QLabel{\n"
"        \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"    border:none;\n"
"\n"
"\n"
"}\n"
"")
        self.label_motivo_reposo.setScaledContents(True)
        self.label_motivo_reposo.setObjectName("label_motivo_reposo")
        self.verticalLayout_3.addWidget(self.label_motivo_reposo)
        self.input_motivo_reposo = QtWidgets.QLineEdit(self.ingresar_reposo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.input_motivo_reposo.sizePolicy().hasHeightForWidth())
        self.input_motivo_reposo.setSizePolicy(sizePolicy)
        self.input_motivo_reposo.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.input_motivo_reposo.setFont(font)
        self.input_motivo_reposo.setStyleSheet("QLineEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    padding-left: 5px;\n"
" padding-right:5px;\n"
"    padding-top:1px;\n"
"    border-bottom:2px solid black  ;\n"
"    border-top: 2px solid rgb(202, 202, 202);\n"
"    border-left: 2px solid rgb(202, 202, 202);\n"
"    border-right: 2px solid rgb(202, 202, 202);\n"
"\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"    border: 2px solid rgb(17, 192, 255)\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.input_motivo_reposo.setObjectName("input_motivo_reposo")
        self.verticalLayout_3.addWidget(self.input_motivo_reposo)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 2)
        self.espacio_fecha_nacimiento = QtWidgets.QFrame(self.ingresar_reposo)
        self.espacio_fecha_nacimiento.setMinimumSize(QtCore.QSize(200, 0))
        self.espacio_fecha_nacimiento.setStyleSheet("QFrame{\n"
"\n"
"\n"
"border:none\n"
"\n"
"\n"
"}")
        self.espacio_fecha_nacimiento.setObjectName("espacio_fecha_nacimiento")
        self.gridLayout = QtWidgets.QGridLayout(self.espacio_fecha_nacimiento)
        self.gridLayout.setObjectName("gridLayout")
        self.label_fecha_solicitud = QtWidgets.QLabel(self.espacio_fecha_nacimiento)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_fecha_solicitud.setFont(font)
        self.label_fecha_solicitud.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.label_fecha_solicitud.setScaledContents(False)
        self.label_fecha_solicitud.setObjectName("label_fecha_solicitud")
        self.gridLayout.addWidget(self.label_fecha_solicitud, 0, 0, 1, 2)
        self.boton_para_agregar_fecha = QtWidgets.QPushButton(self.espacio_fecha_nacimiento)
        self.boton_para_agregar_fecha.setMinimumSize(QtCore.QSize(0, 30))
        self.boton_para_agregar_fecha.setMaximumSize(QtCore.QSize(110, 70))
        self.boton_para_agregar_fecha.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_para_agregar_fecha.setStyleSheet("QPushButton{\n"
"\n"
"    border: 1px solid black;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/calendario.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_para_agregar_fecha.setIcon(icon)
        self.boton_para_agregar_fecha.setIconSize(QtCore.QSize(20, 20))
        self.boton_para_agregar_fecha.setObjectName("boton_para_agregar_fecha")
        self.gridLayout.addWidget(self.boton_para_agregar_fecha, 1, 0, 1, 1)
        self.label_mostrar_fecha_solicitud = QtWidgets.QLabel(self.espacio_fecha_nacimiento)
        self.label_mostrar_fecha_solicitud.setMinimumSize(QtCore.QSize(80, 30))
        self.label_mostrar_fecha_solicitud.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mostrar_fecha_solicitud.setFont(font)
        self.label_mostrar_fecha_solicitud.setText("")
        self.label_mostrar_fecha_solicitud.setObjectName("label_mostrar_fecha_solicitud")
        self.gridLayout.addWidget(self.label_mostrar_fecha_solicitud, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_3.addWidget(self.espacio_fecha_nacimiento, 2, 0, 1, 1)
        self.espacio_fecha_nacimiento_2 = QtWidgets.QFrame(self.ingresar_reposo)
        self.espacio_fecha_nacimiento_2.setMinimumSize(QtCore.QSize(200, 0))
        self.espacio_fecha_nacimiento_2.setStyleSheet("QFrame{\n"
"\n"
"\n"
"border:none\n"
"\n"
"\n"
"}")
        self.espacio_fecha_nacimiento_2.setObjectName("espacio_fecha_nacimiento_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.espacio_fecha_nacimiento_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_fecha_reingreso = QtWidgets.QLabel(self.espacio_fecha_nacimiento_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_fecha_reingreso.setFont(font)
        self.label_fecha_reingreso.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"    border-color: #ffffff;\n"
"\n"
"\n"
"}\n"
"")
        self.label_fecha_reingreso.setScaledContents(False)
        self.label_fecha_reingreso.setObjectName("label_fecha_reingreso")
        self.gridLayout_2.addWidget(self.label_fecha_reingreso, 0, 0, 1, 2)
        self.boton_para_agregar_fecha_2 = QtWidgets.QPushButton(self.espacio_fecha_nacimiento_2)
        self.boton_para_agregar_fecha_2.setMinimumSize(QtCore.QSize(0, 30))
        self.boton_para_agregar_fecha_2.setMaximumSize(QtCore.QSize(110, 70))
        self.boton_para_agregar_fecha_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_para_agregar_fecha_2.setStyleSheet("QPushButton{\n"
"\n"
"    border: 1px solid black;\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color: rgb(199, 199, 199)\n"
"}")
        self.boton_para_agregar_fecha_2.setIcon(icon)
        self.boton_para_agregar_fecha_2.setIconSize(QtCore.QSize(20, 20))
        self.boton_para_agregar_fecha_2.setObjectName("boton_para_agregar_fecha_2")
        self.gridLayout_2.addWidget(self.boton_para_agregar_fecha_2, 1, 0, 1, 1)
        self.label_mostrar_fecha_reingreso = QtWidgets.QLabel(self.espacio_fecha_nacimiento_2)
        self.label_mostrar_fecha_reingreso.setMinimumSize(QtCore.QSize(80, 30))
        self.label_mostrar_fecha_reingreso.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_mostrar_fecha_reingreso.setFont(font)
        self.label_mostrar_fecha_reingreso.setText("")
        self.label_mostrar_fecha_reingreso.setObjectName("label_mostrar_fecha_reingreso")
        self.gridLayout_2.addWidget(self.label_mostrar_fecha_reingreso, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_3.addWidget(self.espacio_fecha_nacimiento_2, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.boton_anadir_reposo = QtWidgets.QPushButton(self.ingresar_reposo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boton_anadir_reposo.sizePolicy().hasHeightForWidth())
        self.boton_anadir_reposo.setSizePolicy(sizePolicy)
        self.boton_anadir_reposo.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.boton_anadir_reposo.setFont(font)
        self.boton_anadir_reposo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.boton_anadir_reposo.setStyleSheet("QPushButton{\n"
"\n"
"    \n"
"    background-color: rgb(0, 138, 71);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    \n"
"    background-color: rgb(0, 56, 10);\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(BASE_DIR, "../recursos_de_imagenes/iconos_de_interfaz/control_de_reposos.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boton_anadir_reposo.setIcon(icon1)
        self.boton_anadir_reposo.setIconSize(QtCore.QSize(20, 20))
        self.boton_anadir_reposo.setObjectName("boton_anadir_reposo")
        self.gridLayout_3.addWidget(self.boton_anadir_reposo, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        self.gridLayout_3.setRowStretch(2, 40)
        self.verticalLayout_4.addWidget(self.ingresar_reposo, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.espacio_principal)

        self.retranslateUi(VentanaAnadirReposo)
        QtCore.QMetaObject.connectSlotsByName(VentanaAnadirReposo)

    def retranslateUi(self, VentanaAnadirReposo):
        _translate = QtCore.QCoreApplication.translate
        VentanaAnadirReposo.setWindowTitle(_translate("VentanaAnadirReposo", "Form"))
        self.titulo.setText(_translate("VentanaAnadirReposo", "Control de reposos"))
        self.label_cedula.setText(_translate("VentanaAnadirReposo", "Cédula del empleado/personal"))
        self.input_cedula.setPlaceholderText(_translate("VentanaAnadirReposo", "....."))
        self.label_motivo_reposo.setText(_translate("VentanaAnadirReposo", "Motivo del reposo"))
        self.input_motivo_reposo.setPlaceholderText(_translate("VentanaAnadirReposo", "....."))
        self.label_fecha_solicitud.setText(_translate("VentanaAnadirReposo", "Fecha de solicitud"))
        self.boton_para_agregar_fecha.setText(_translate("VentanaAnadirReposo", "Agregar fecha"))
        self.label_fecha_reingreso.setText(_translate("VentanaAnadirReposo", "Fecha de reingreso"))
        self.boton_para_agregar_fecha_2.setText(_translate("VentanaAnadirReposo", "Agregar fecha"))
        self.boton_anadir_reposo.setText(_translate("VentanaAnadirReposo", "Añadir reposo"))